### PR TITLE
TINKERPOP-1653 Allow multiple scripts to be passed to gremlin.sh

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1653

This is a non-breaking change and simply allows multiple `-i` and `-e` options on gremlin.sh. The old method for passing a single script name to gremlin.sh remains intact as well. Had to write a custom parser for the command line arguments to do this because it doesn't appear that `CliBuilder` is capable of parsing the in the manner necessary to support this feature unfortunately.

Here's some example usage given these three scripts:

```text
$ more *.groovy
::::::::::::::
x.groovy
::::::::::::::
x = 1 + 1
::::::::::::::
y.groovy
::::::::::::::
y = args.collect{Integer.parseInt(it)}.sum()
::::::::::::::
z.groovy
::::::::::::::
z = "argument=" + args
```

This is old, now deprecated, method that is still supported:

```
$ bin/gremlin.sh x.groovy 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> x
==>2
```

Next with `-i` as usual:

```text
$ bin/gremlin.sh -i x.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> x
==>2
```

then with arguments:

```text
$ bin/gremlin.sh -i y.groovy 1 2 3

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> y
==>6
```

Next with multiple scripts:

```text
$ bin/gremlin.sh -i y.groovy 1 2 3 -i x.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> y
==>6
gremlin> x
==>2
```

Then with multiple scripts with other `gremlin.sh` options mixed in

```text
$ bin/gremlin.sh -i y.groovy 1 2 3 --color -i x.groovy -i "z.groovy x -i --color -D"

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> x
==>2
gremlin> y
==>6
gremlin> z
==>argument=[x, -i, --color, -D]
```

Finally, note that you still can't mix/match `-i` and `-e` commands - `CliBuilder` still rejects bad stuff like that:

```text
$ bin/gremlin.sh -i y.groovy 1 2 3 --color -i x.groovy -e "z.groovy x -i --color -D"
-i and -e options are mutually exclusive - provide one or the other
```

VOTE +1

### CODE REVIEW

**Comment by twilmes** [comment]
I experimented with variations of arguments and all looked good.

VOTE: +1

**Comment by robertdale** [comment]
might want to add these scripts/test to `validate-distribution.sh`

**Comment by spmallette** [comment]
I think I got good stuff for you @robertdale - please have a look.

**Comment by robertdale** [comment]
Fantastic! Verified tests.
VOTE +1

**Pull request merged**
