### PR TITLE
TINKERPOP-2951: add translator to the Go GLV

### PR DESCRIPTION
**Pull request by itaywol**
This readdresses the following PR https://github.com/apache/tinkerpop/pull/2157
But moved the commits to 3.5-dev as base branch

### CODE REVIEW

**Comment by itaywol** [comment]
@Cole-Greer @vkagamlyk Indeed more test were required, it inflated a little due to the fact i had to use reflection to open some of the struct underlying the interfaces

**Comment by Cole-Greer** [comment]
Hi Itay,

Thanks for all the rapid changes to the PR. To build off of Valentyn’s comments once again, I think there are still additional types that will need to be supported in order for the translator to be considered complete. Support for the following will all be needed:

- Translation of nested structures (within lists and maps)
- Primitive types (Char, Byte/int8, Short/int16)
- More common structure types (Date, Datetime, UUID, BigInteger, BigDecimal)
- Strategies

The [python translator](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/gremlin_python/process/translator.py) is a good reference to follow for this.
There is still an opportunity for this to be merged tomorrow morning (Thursday in the Americas) if its complete although the release process is already well underway so this would be the final chance to make it into the upcoming release. If there is only minor tweaks needed tomorrow morning we may be able to assist with getting it finished up and into the release.

Thanks,

Cole

**Comment by Cole-Greer** [comment]
Hi @itaywol, I just wanted to check in here as a bit of time has now passed. Do you still intend to return to this PR at some point? Is there anything we can help with to drive this work to completion?

**Comment by itaywol** [comment]
Hey @Cole-Greer, I am actually working now on better implementation for this PR i will open new one today or tomorrow

**Comment by itaywol** [comment]
@Cole-Greer What should be my base branch?

**Pull request closed without merging**
