### PR TITLE
Add PR template.

### PR DESCRIPTION
**Pull request by kenhuuu**
Adding a template based on the dev list DISCUSS thread found here https://lists.apache.org/thread/63r2lzv69yf0odvwbz111yckvx7q10of

### CODE REVIEW

**Comment by Cole-Greer** [comment]
Thanks Ken, LGTM
VOTE +1

**Comment by kenhuuu** [comment]
> I don't mean to be overly focused on number of words, but if this takes too long to read, it might not have the desired effect.

I agree with this and have tried to explain the target branch in as few words as possible, but couldn't quite shorten it down anymore. I feel the need to explain our branch management strategy as it seems to be slightly different than other projects and a common source of confusion for new contributors.

> (2) more formatting to draw the eye to stuff that matters.

Also agree, but I'm limited on what I can do here based on this being a hidden comment that won't render formatting.

**Comment by vkagamlyk** [comment]
VOTE +1

**Comment by kenhuuu** [comment]
VOTE +1

**Pull request merged**
