### PR TITLE
TINKERPOP-1760: OLAP compilation failing around ConnectiveStrategy

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1760

The more general problem was in `ComputerVerificationStrategy`. The problem was the nested traversals were being analyzed prior to full strategy compilation. The solution actually simplified the code a bit.

```
gremlin> g = TinkerFactory.createModern().traversal().withComputer()
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], graphcomputer]
gremlin> g.V().where(out("created").and().out("knows")).values("name")
==>marko
```

VOTE +1

### CODE REVIEW

**Comment by dkuppitz** [comment]
Any reason why this shouldn't go into `tp32/`?

**Comment by okram** [comment]
No. I just spaced on selecting `tp32/` and left it defaulted at `master/`. Fixed.

**Comment by dkuppitz** [comment]
`docker/build.sh -t -i` succeeded.

VOTE: +1

**Comment by okram** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:21 h
[INFO] Finished at: 2017-08-28T16:04:55-06:00
[INFO] Final Memory: 162M/1646M
[INFO] ------------------------------------------------------------------------
```

**Comment by spmallette** [comment]
All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Pull request merged**
