### PR TITLE
TINKERPOP-1692 Neo4j 3.2.2

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1692

Bumps to Neo4j 3.2.2 and is the revision to #674 which needed some additional `pom.xml` work. That's the only real change here. Going forward for review/vote purposes, we'll use this PR over the other one.

Running full tests now....will udpate when complete.

### CODE REVIEW

**Comment by robertdale** [comment]
@spmallette Sorry I haven't commented earlier. I don't think this is right.  This PR is using neo4j-tinkerpop-api-impl 0.6-3.2.2 which uses gremlin 3.2.5. However, master is gremlin 3.3.0-SNAPSHOT.

**Comment by spmallette** [comment]
confused - does this mean this PR should target 3.2.2? or is there a neo4j-tinkerpop-api-impl 0.6-3.3.0 to use?

**Comment by robertdale** [comment]
The original request was to upgrade on TinkerPop 3.3 on https://github.com/neo4j-contrib/neo4j-tinkerpop-api-impl/issues/6 .  I think with Neo4j and TinkerPop being on similar 3.x.y version schemes, that it got mixed up.  

@jexp  Did you perhaps have another api-impl branch based on TinkerPop 3.3.0?

**Comment by robertdale** [comment]
Hmm... so just to reiterate and be super clear the desire is to have Neo4j 3.2.2 on TinkerPop 3.3.0.

**Comment by spmallette** [comment]
ok - well, i'll leave this branch where it is and let you roll with it then.  if you want me to just close it, then let me know.

**Comment by jexp** [comment]
I didn't see a released 3.3.0 version of tp3 on maven central, that's why I used 3.2.5

**Comment by spmallette** [comment]
3.3.0 is still SNAPSHOT only. it won't release for another couple of weeks or so i imagine.

**Comment by jexp** [comment]
I pushed a branch here: https://github.com/neo4j-contrib/neo4j-tinkerpop-api-impl/tree/gremlin-330
and updated the other branch here: https://github.com/jexp/incubator-tinkerpop/commit/30a37b2cbdaabdd825271bd5991a376a254fbd0f
with the version upgrade to 0.7-3.2.2-SNAPSHOT

**Comment by robertdale** [comment]
Pulled in @jexp latest changes.  This depends on SNAPSHOT versions both ways (cyclic dependencies) so we'll need to update both sides to release versions at release time.
`mvn clean install -pl neo4j-gremlin -am -ff -DskipIntegrationTests=false -DincludeNeo4j ` BUILD SUCCESS

**Comment by spmallette** [comment]
@robertdale can you offer your thoughts on how you see this working? I don't think we want to merge a SNAPSHOT to master.

**Comment by robertdale** [comment]
@spmallette I think the right way to do it is for @jexp to pull out that neo4j/gremlin procedure into its own, separate module. That's what creates the cyclic dependency on tinkerpop. Then a proper release of neo4j-tinkerpop-api-impl can be made.  @jexp thoughts?

**Comment by jexp** [comment]
@robertdale I did the split of the project into two modules which have been published separately, please have a look.

http://search.maven.org/#artifactdetails%7Corg.neo4j%7Cneo4j-tinkerpop-api-impl%7C0.7-3.2.3%7Cjar

**Comment by robertdale** [comment]
`docker/build.sh -i -t -n` SUCCESS
VOTE +1

**Comment by robertdale** [comment]
I did a rebase to master and messed it up.

**Comment by robertdale** [comment]
All better now.  Verified new index and cluster property settings.
VOTE +1 again

**Comment by spmallette** [comment]
All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
