### PR TITLE
Add additional information to TimeoutExceptions.

### PR DESCRIPTION
**Pull request by kenhuuu**
Provides users with potentially more information when the driver times out waiting for a connection.

### CODE REVIEW

**Comment by vkagamlyk** [comment]
LGTM VOTE +1

Thanks @kenhuuu

**Comment by lyndonbauto** [comment]
VOTE+1

**Comment by Cole-Greer** [comment]
LGTM.  This added detail to timeout exceptions will be helpful.

**Comment by xiazcy** [comment]
VOTE +1, merging this today. Thanks Ken!

**Pull request merged**
