### PR TITLE
TINKERPOP-2526 Add imports to the Console via an ImportCustomizer.

### PR DESCRIPTION
**Pull request by kenhuuu**
Adding imports by providing the CompilerConfiguration with an ImportCustomizer greatly improves performance because the imports won't be resolved again for each complete line in a script.

### CODE REVIEW

**Comment by vkagamlyk** [comment]
VOTE +1

**Comment by Cole-Greer** [comment]
Previously building the docs was impossibly slow on any groovy version beyond 2.5.15. What is the doc building performance on newer versions of groovy with these changes included?

**Comment by spmallette** [comment]
wow - hard to believe this was the fix all this time. incredible job getting to the bottom of this and working with the Groovy Community to help solve it. this fix unlocks a lot of blockages. hero! 🏅 

needs a CHANGELOG entry, but other than that:

VOTE +1

**Comment by kenhuuu** [comment]
> Previously building the docs was impossibly slow on any groovy version beyond 2.5.15. What is the doc building performance on newer versions of groovy with these changes included?

With these changes and Groovy 2.5.17 (a version we noticed a slowdown with), the 3.5.5 documentation processing took roughly 25 min. The 3.5.5 release code takes about 90m to do the same documentation processing.

**Comment by kenhuuu** [comment]
VOTE + 1

**Pull request merged**
