### PR TITLE
Ensure serializers iteration is consistent

### PR DESCRIPTION
**Pull request by aboudreault**
@spmallette the goal of this PR is simply to avoid inconsistency between different executions, as we experienced.

### CODE REVIEW

**Comment by aboudreault** [comment]
Done

**Comment by spmallette** [comment]
Makes sense to me. gremlin-python tests are passing so....

VOTE +1

**Comment by davebshow** [comment]
Vote +1

**Comment by okram** [comment]
VOTE +1

**Comment by spmallette** [comment]
Merged to tp32 and master - thanks @aboudreault

**Pull request merged**
