### PR TITLE
TINKERPOP-1871: improve performance by not handling excepptions

### PR DESCRIPTION
**Pull request by artem-aliev**

### CODE REVIEW

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
I think this could be re-targetted at the tp32 branch - is there any reason not to @artem-aliev ?

**Comment by spmallette** [comment]
I'm posting this to all open PRs of current relevance - this PR needs to be rebased against the branch it is targeted against given a broken python dependency that was published to pypi a day or so ago. I've pushed a fix on tp32 and master at this point and David Brown is working on getting an issue raised with the project that initiated the problem.

**Comment by artem-aliev** [comment]
retargeted/rebase to latest tp32

**Comment by jorgebay** [comment]
lgtm! VOTE: +1

**Pull request merged**
