### PR TITLE
Expose Pick in module.exports

### PR DESCRIPTION
**Pull request by arings**
#460 so `Pick.any` and `Pick.none` can be used in gremlin-javascript.

### CODE REVIEW

**Comment by jorgebay** [comment]
Looks good, thanks @arings !

VOTE: +1

I've filed a ticket to keep track of this bug fix: TINKERPOP-2009.

Committers: note that we should merge it to `tp32`.

**Comment by spmallette** [comment]
@jorgebay any reason this wasnt noted in GLV tests? are we missing a scenario?

**Comment by jorgebay** [comment]
`Pick` is covered by the cucumber tests and those features are passing: https://github.com/apache/tinkerpop/blob/master/gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js#L190

The problem is that we weren't exporting `pick` enum for users to access it.

**Comment by spmallette** [comment]
VOTE +1

**Comment by jorgebay** [comment]
Cherry picked and landed in c324002c7d2184b87ef1e90067c318ebf727311f (`tp32`, `tp33` and `master`).

Thanks @arings!

**Pull request closed without merging**
