### PR TITLE
TINKERPOP-1525 Avoid starting VP worker iterations that never end

### PR DESCRIPTION
**Pull request by dalaro**
SparkExecutor.executeVertexProgramIteration was written in such a way
that an empty RDD partition would cause it to invoke
VertexProgram.workerIterationStart without ever invoking
VertexProgram.workerIterationEnd.  This seems like a contract
violation.  I have at least one VP that relies on
workerIterationStart|End to allocate and release resources.  Failing
to invoke End like this causes a leak in that VP, as it would for any
VP that uses that resource management pattern.

### CODE REVIEW

**Comment by okram** [comment]
Ah. Yea -- huh. Total odd ball case, but yea, you are right. The empty iterator would make it so the end iteration never fires. 

VOTE +1.

**Comment by spmallette** [comment]
Travis is showing a pretty clear compilation failure:

```text
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spark-gremlin: Compilation failure
[ERROR] /home/travis/build/apache/tinkerpop/spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkExecutor.java:[92,37] incompatible types: no instance(s) of type variable(s) T exist so that java.util.Iterator<T> conforms to java.lang.Iterable<scala.Tuple2<K2,V2>>
```

can that be ignored?

**Comment by okram** [comment]
This is because @dalaro is working against TINKERPOP-1389 which is Spark 2.0. Spark 1.x returns `Iterable`, not `Iterator`. Simple to fix.

**Comment by dalaro** [comment]
Marko's right, I wrote and tested this against TINKERPOP-1389 (before the latest rebase), then cherry-picked against current master without retesting.  Sorry about that.  He's also right about the Iterator/Iterable change.  I'll change it sometime today, force-push the branch, and comment.

**Comment by dalaro** [comment]
I force-pushed this branch with a fix (`emptyIterator -> emptyList`).

**Comment by dalaro** [comment]
I made a version of this change for TINKERPOP-1389 as #466.  That one's optional, but I thought merging this into TINKERPOP-1389 might help ensure this fix does not get lost in the eventual possibly-conflict-y and confusing merge of TINKERPOP-1389 to master.

**Comment by okram** [comment]
VOTE +1

**Comment by spmallette** [comment]
@okram did you understand the nature of the comment @dalaro made about #466 ? 

All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
