### PR TITLE
use embed for error/logger resources

### PR DESCRIPTION
**Pull request by remiphilippe**
following the discussion here: https://groups.google.com/g/gremlin-users/c/rSWrioOk58U

the logger and error files are trying to be loaded at runtime from the repo code, but when the binaries are used it can't find the resources files.
So all errors / logger appear as:
`%!(EXTRA string=ws://localhost:50639/gremlin)`

when using embed(https://pkg.go.dev/embed) the resources files loaded with the binary.
The messages now display properly:
`Closing DriverRemoteConnection with url 'ws://localhost:49696/gremlin'`

### CODE REVIEW

**Comment by vkagamlyk** [comment]
Remi thank you for PR!

Smoke tests failed because missing headers with Apache license in generated files

**Comment by remiphilippe** [comment]
working on fixing that, thanks!

**Comment by remiphilippe** [comment]
should work now. Moved to `embed` and added the copyright

**Comment by vkagamlyk** [comment]
VOTE +1

**Comment by xiazcy** [comment]
Thanks for the changes and sorry for the delay. I just noticed we should target to 3.5-dev for this change, so I will cherry pick the commits and merge them to 3.5-dev for this.

**Comment by xiazcy** [comment]
Closing this PR as I will be merging all changes cherry-picked through this PR: https://github.com/apache/tinkerpop/pull/1851

**Pull request closed without merging**
