### PR TITLE
Gremlin Arrow Flight Proposal

### PR DESCRIPTION
**Pull request by vkagamlyk**
Added proposal document for Arrow Flight usage

### CODE REVIEW

**Comment by joshsh** [comment]
"Gremlin Server and drivers should replace the network layer with Arrow Flight" --> What factors make it infeasible to support WebSocket and Arrow Flight in parallel?

**Comment by vkagamlyk** [comment]
> "Gremlin Server and drivers should replace the network layer with Arrow Flight" --> What factors make it infeasible to support WebSocket and Arrow Flight in parallel?

My goal is to simplify development and support. WebSocket and Arrow Flight in parallel is a complication

**Comment by joshsh** [comment]
> 

You don't think it would be safer to leave the WebSocket solution intact until the Arrow Flight solution has proven itself end-to-end? Stage 1, in this proposal, already involves replacing the transport layer.

**Comment by vkagamlyk** [comment]
> > 
> 
> You don't think it would be safer to leave the WebSocket solution intact until the Arrow Flight solution has proven itself end-to-end? Stage 1, in this proposal, already involves replacing the transport layer.

I think it's not difficult to use another endpoint for Arrow Flight and keep existing WebSocket solution for a transitional period

**Comment by joshsh** [comment]
> I think it's not difficult to use another endpoint for Arrow Flight and keep existing WebSocket solution for a transitional period

I suggest updating the proposal to reflect that.
Stage 0: clone the end-to-end WebSocket solution and begin migrating it to Arrow Flight, keeping the original solution intact
Stage n: assess the WebSocket solution and retire it if no longer needed

**Comment by joshsh** [comment]
Even at Stage n, caution will be necessary. I believe there are plenty of "dark" Gremlin clients which aren't part of the official code base or known Gremlin variants, and talk directly to Gremlin Server using WebSocket.

**Comment by spmallette** [comment]
Thanks for submitting this proposal for discussion. I see this targets version 4.x. Maybe it's ok to take the big break there from websockets. If this proposal were targeting 3.x, we'd have to keep websocket communication for sure. 

If the proposal sticks to targeting 4.x then it seems like one of the big questions affecting the staging of an implementation would be a schema proposal for 4.x. I assume having that proposal would help you understand how to use the standard flight serialization and thus skip past using the current serializers as part of this implementation.

**Comment by joshsh** [comment]
Ah, I didn't realize this was targeted at 4.x only. Disregard my "hot swap" concerns, then. For schema, I would like to take a common specification of a TinkerPop model like [this](https://github.com/CategoricalData/hydra/blob/main/hydra-haskell/src/main/haskell/Hydra/Impl/Haskell/Sources/Ext/Tinkerpop/V3.hs) or [this](https://github.com/CategoricalData/hydra/blob/main/hydra-haskell/src/main/haskell/Hydra/Impl/Haskell/Sources/Ext/Tinkerpop/Typed.hs) and transform it into concrete APIs like [this](https://categoricaldata.github.io/hydra/hydra-java/javadoc/hydra/ext/tinkerpop/v3/package-summary.html) in a number of languages (Java, Scala, Haskell right now; working on Python support, and there will be others). We should take a fresh look at requirements for the schema language.

**Pull request merged**
