### PR TITLE
TINKERPOP-1848 use generated datetime to ignore timezone, DST differences in test

### PR DESCRIPTION
**Pull request by robertdale**
https://issues.apache.org/jira/browse/TINKERPOP-1848

### CODE REVIEW

**Comment by robertdale** [comment]
`docker/build.sh -t` BUILD SUCCESS
VOTE +1

**Comment by jorgebay** [comment]
I think this should be targeted to `tp32` branch.

**Comment by robertdale** [comment]
Yeah, I didn't initially see it in tp32.  This is not the right approach anyway. Will push an update.

**Comment by robertdale** [comment]
Fixed test only.
Tests pass.
VOTE +1

**Comment by spmallette** [comment]
VOTE +1

**Comment by jorgebay** [comment]
VOTE +1

**Pull request merged**
