### PR TITLE
[TINKERPOP-3014] Reorder the jcl-over-slf4j dependency to avoid the dependency conflict.

### PR DESCRIPTION
**Pull request by HappyHacker123**
Related to https://issues.apache.org/jira/browse/TINKERPOP-3014. 
Dependencny jcl-over-slf4j in gremlin-core is declared but unused due to dependency conflict, change the order so that the jcl-over-slf4j exceeds commons-logging in classpath.

### CODE REVIEW

**Comment by vkagamlyk** [comment]
Hi @HappyHacker123,
Would you like to see this changes in 3.5.x, 3.6.x or 3.7.x? 
You opened PR to `master`, but this branch in not for release now.

**Comment by Cole-Greer** [comment]
I don't have any issues with the reordering, other than I would prefer to move all slf4j dependencies together to maintain organization.
```        <!-- LOGGING -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
        </dependency>
```
Other than that I'm fine with the changes, as @vkagamlyk please rebase to an earlier branch to include this fix in an earlier release line. For example, rebase it to 3.6-dev to have this included in both 3.6.6 and 3.7.1. If you only need it in 3.7.1 then it should be targetted to 3.7-dev.

**Comment by HappyHacker123** [comment]
>  Would you like to see this changes in 3.5.x, 3.6.x or 3.7.x?

I think 3.7.x is fine :), i will rebase to 3.7-dev and open anthoer pr.
> I don't have any issues with the reordering, other than I would prefer to move all slf4j dependencies together to maintain organization.

Sure, i will add the changes.

**Comment by HappyHacker123** [comment]
I raise a pr #2349 that adapt the changes and change the base branch. Close this pr.

**Pull request closed without merging**
