### PR TITLE
ResultSet.hasNext should be idempotent

### PR DESCRIPTION
**Pull request by robertdale**
Sorry I didn't create a ticket; JIRA is having problems.

Calling hasNext() multiple times would dequeue items.

### CODE REVIEW

**Comment by spmallette** [comment]
This looks like a good change. Thanks for this. Did you run the Gremlin Server integration tests after making this change?

**Comment by robertdale** [comment]
Yes, I ran 'mvn clean install -DskipIntegrationTests=false -DincludeNeo4j' and it passed.

**Comment by spmallette** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
@robertdale when we get the final vote for this PR to be merged, i expect to merge it to tp31 and then master as I'd like the 3.1.x line of code to get this fix. i only mention this because i see that you now have what looks like an empty merge commit on this PR at this point. Do you know what that is? Is that something you can clean up from your end?

note to the final voter - i will update changelog on merge.

**Comment by robertdale** [comment]
I merged your master into my fork. Commit 0787e46097cc09bb278ac1c787c4a50ece81cdb0
I didn't realize it would affect the pull request. Next time I'll create a branch.

**Comment by spmallette** [comment]
You could just use `git rebase` to update your branch rather than `git merge` - in that way the commit history doesn't get weird.

**Comment by robertdale** [comment]
Normally that's what I would do but tried doing it the 'github way' - https://help.github.com/articles/syncing-a-fork/

So let me know what you want me to do now.  I can start over, creating the JIRA ticket, branch, etc.

**Comment by spmallette** [comment]
no need to start over - maybe not an issue. i'll see what happens when i merge. thanks

**Comment by okram** [comment]
Smart. VOTE +1.

**Pull request closed without merging**
