### PR TITLE
Fix Sack Split.

### PR DESCRIPTION
**Pull request by RainMark**
Why sack spliter use the initial sack?

### CODE REVIEW

**Comment by robertdale** [comment]
Is there a test that covers this?

**Comment by RainMark** [comment]
Nop,there is no test for sack split operator. 
If I pass in a special split operator, this operator can't obtain source traverser's sack value with apply() method.

**Comment by robertdale** [comment]
@RainMark Could you create an issue in Jira and describe the problem?   See also [Contributing code changes](https://tinkerpop.apache.org/docs/current/dev/developer/#_contributing_code_changes). It would be good to see a test case that fails without the change and passes with the change but also satisfies the examples in the documentation.

I also want to make sure you're not running into this
- http://tinkerpop.apache.org/docs/current/reference/#sack-step
```
The first example does not use a split operator and as such, the same map is propagated to
all traversers (a global data structure). The second example, demonstrates how Map.clone()
ensures that each traverser’s sack contains a unique, local sack.
```

**Comment by spmallette** [comment]
@RainMark did you have a chance to consider the previous comment from @robertdale ?  While I appreciate that you have a solution to a problem you are seeing, I share his concern about understanding the nature of the problem itself that is being fixed.

**Comment by spmallette** [comment]
hi @RainMark do you plan to come back to address the comments here?

**Comment by RainMark** [comment]
@spmallette yes,I will come back to address the comments. just a little busy recently

**Comment by RainMark** [comment]
@spmallette @robertdale 

The sack of clone traverser is correctly.
Sorry, I'm new for java, I never noticed Java's object clone method.
Recently, We develop a gremlin query engine based on c++, So I ask this question.
Anyway,Thank you very much!

**Comment by spmallette** [comment]
> We develop a gremlin query engine based on c++,

interesting....Is that code available as open source?

**Pull request closed without merging**
