### PR TITLE
Release name generator

### PR DESCRIPTION
**Pull request by robertdale**
$ groovy release-name-generator.groovy 
Twenty-Four Gremlin From Tulsa
$ groovy release-name-generator.groovy 
(I'd) Wait a Million Gremlin
$ groovy release-name-generator.groovy 
Two Gremlin
$ groovy release-name-generator.groovy 
Twelve Gremlin of Christmas
$ groovy release-name-generator.groovy 
1, 2, 3, Red Gremlin
$ groovy release-name-generator.groovy 
1 Gremlin
$ groovy release-name-generator.groovy 
Twelve Volt Gremlin

### CODE REVIEW

**Comment by okram** [comment]
Ha. For sure this is bad ass, but I don't know about putting it into the repo...  Well, perhaps off `bin/` or something.... dunno.

VOTE +0.

**Comment by robertdale** [comment]
That's ok. I don't actually expect this to get merged. Just for fun. This was a convenient way to share.

**Comment by spmallette** [comment]
Neat use of Gremlin - fun! Not sure if there's a tutorial to built out of it or something?

**Comment by robertdale** [comment]
Inaugurated my blog and forever immortalized at https://robertdale.github.io/2016/09/15/gremlin-create-gremlin-release-name.html

**Comment by spmallette** [comment]
You should post a link to that on gremlin-users :)

**Pull request closed without merging**
