### PR TITLE
TINKERPOP-1749  Bump to Netty 4.0.50

### PR DESCRIPTION
**Pull request by robertdale**
https://issues.apache.org/jira/browse/TINKERPOP-1749

Many SSL updates, bug fixes.

`docker/build.sh -i -t -n` SUCCESS

VOTE +1

### CODE REVIEW

**Comment by spmallette** [comment]
Ran Gremlin Server integration tests to success. Did you double check to make sure that no new dependencies came down with this version bump (i.e. nothing new in the zip distribution)?

VOTE +1

**Comment by robertdale** [comment]
@spmallette Confirmed no new deps in zip.

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
before merging this one @robertdale would you mind rebasing your PR on tp32 and testing docs just to be sure this doesn't cause trouble.

**Comment by robertdale** [comment]
@spmallette docs success

**Pull request merged**
