### PR TITLE
TINKERPOP-1440: g:Path needs a GraphSON deserializer in Gremlin-Python

### PR DESCRIPTION
**Pull request by okram**
This was easy to implement. Now you get a Path `Path` object back with a `str` that looks like Gremlin-Python.

CHANGELOG:

```
* Added Path to Gremlin-Python with respective GraphSON 2.0 deserializer
```

### CODE REVIEW

**Comment by twilmes** [comment]
VOTE: +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by okram** [comment]
VOTE +1.

**Comment by davebshow** [comment]
VOTE +1

**Pull request merged**
