### PR TITLE
TINKERPOP-1642 Performance Enhancement on Mutating Traversal Execution

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1642

This is a focused effort to improve the performance of traversals that mutate the graph.  All improvements were made on gremlin-core and should therefore be helpful to all `Graph` implementations. Here's the benchmarks at 3.2.4:

```text
Benchmark                                           Mode  Cnt        Score         Error  Units
GraphMutateBenchmark.testAddE                      thrpt   20    20010.155 ±     621.783  ops/s
GraphMutateBenchmark.testAddEdge                   thrpt   20  3609684.997 ±  195545.641  ops/s
GraphMutateBenchmark.testAddV                      thrpt   20   288621.370 ±   12576.655  ops/s
GraphMutateBenchmark.testAddVAddEWithPropsChained  thrpt   20        5.402 ±       0.084  ops/s
GraphMutateBenchmark.testAddVWithProps             thrpt   20    21924.945 ±     230.668  ops/s
GraphMutateBenchmark.testAddVWithPropsChained      thrpt   20      184.896 ±       4.875  ops/s
GraphMutateBenchmark.testAddVertex                 thrpt   20  5830447.734 ±  131727.984  ops/s
GraphMutateBenchmark.testAddVertexWithProps        thrpt   20   163131.738 ±    2647.117  ops/s
GraphMutateBenchmark.testEdgeProperty              thrpt   20  8971499.256 ± 1630382.353  ops/s
GraphMutateBenchmark.testEdgePropertyStep          thrpt   20   125053.249 ±    4770.478  ops/s
GraphMutateBenchmark.testVertexProperty            thrpt   20  3741129.376 ±  286173.817  ops/s
GraphMutateBenchmark.testVertexPropertyStep        thrpt   20   121742.106 ±    4339.508  ops/s
```

and here's the benchmarks now in this PR which will apply to 3.2.5 and 3.3.0:

```text
Benchmark                                           Mode  Cnt        Score        Error  Units
GraphMutateBenchmark.testAddE                      thrpt   20    26921.570 ±    241.374  ops/s
GraphMutateBenchmark.testAddEdge                   thrpt   20  3567550.566 ± 185748.638  ops/s
GraphMutateBenchmark.testAddV                      thrpt   20   341523.214 ±  10678.074  ops/s
GraphMutateBenchmark.testAddVAddEWithPropsChained  thrpt   20      462.173 ±     46.842  ops/s
GraphMutateBenchmark.testAddVWithProps             thrpt   20    46946.475 ±    508.174  ops/s
GraphMutateBenchmark.testAddVWithPropsChained      thrpt   20      430.650 ±      5.941  ops/s
GraphMutateBenchmark.testAddVertex                 thrpt   20  6362284.245 ± 294203.426  ops/s
GraphMutateBenchmark.testAddVertexWithProps        thrpt   20   165223.769 ±   4788.481  ops/s
GraphMutateBenchmark.testEdgeProperty              thrpt   20  8490043.427 ± 575562.362  ops/s
GraphMutateBenchmark.testEdgePropertyStep          thrpt   20   142430.605 ±   3452.101  ops/s
GraphMutateBenchmark.testVertexProperty            thrpt   20  4016719.775 ± 587856.207  ops/s
GraphMutateBenchmark.testVertexPropertyStep        thrpt   20   131740.946 ±   1525.710  ops/s
```

The key things to note:

* A simple `g.addV()` got about 20% faster 
* A simple `g.addE()` got about 34% faster
* A long chained set of `addV()` where multiple vertices were added in a single traversal became a bit more than twice as fast.
* A long chained set of `addV()` and `addE()` where multiple vertices/edges were added in a single traversal became 92 times faster
* These changes did not hurt performance of the "non-mutating" traversals - those benchmarks remained about the same.

Obviously, these numbers still lag where we want to be, but the changes in place represent a good body of work at this point and have opened up other ideas for improvements which can be dealt with as other specific issues/pull requests.

VOTE +1

### CODE REVIEW

**Comment by dkuppitz** [comment]
`docker/build.sh -t -n -i` failed.

Got an NPE in `SparkGraphComputerGroovyProcessIntegrateTest`.

**Comment by spmallette** [comment]
Yeah - @okram mentioned the same thing. I thought it had passed for me earlier. I had a number of builds running on different systems. I think I attributed that failure to a different branch by mistake. Anyway - now that we've confirmed that there is a build issue, I wonder what the problem is. I don't recall doing anything with `sack()` in this change. Judging from the failing line, it looks like `sideEffects` field in `B_LP_O_S_SE_SL_Traverser` is null.

**Comment by okram** [comment]
Note that `tp32/` doesn't have the issue. Thus, the bug is confined to this branch (luckily).

**Comment by twilmes** [comment]
This is an impressive set of performance improvements. I was testing and ran into an issue with this following query.  It ran successfully against `tp32`.

```
graph = TinkerGraph.open()
g = graph.traversal()
g.addV().as("first").repeat(addE("next").to(addV()).inV()).times(5).addE("next").to(select("first"))

java.lang.IllegalStateException: The traversal strategies are complete and the traversal can no longer be modulated
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal$Exceptions.traversalIsLocked(Traversal.java:274)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:112)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:129)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:186)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.apache.tinkerpop.gremlin.console.Console$_closure3.doCall(Console.groovy:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ...
```

**Comment by spmallette** [comment]
weird @twilmes - i wonder what that traversal is doing that none of our tests are doing.

**Comment by okram** [comment]
Fixed the bugs that both @dkuppitz and @twilmes discovered.

VOTE +1.

**Comment by dkuppitz** [comment]
`docker/build.sh -t -n -i` succeeded.

VOTE: +1

**Comment by robertdale** [comment]
My app tests pass. Also noticed a slight reduction in test time. :grinning:

VOTE +1

**Pull request merged**
