### PR TITLE
[TINKERPOP-3027] Replace Pick.any with Pick.any_

### PR DESCRIPTION
**Pull request by ryn5**
https://issues.apache.org/jira/projects/TINKERPOP/issues/TINKERPOP-3027

### CODE REVIEW

**Comment by spmallette** [comment]
thanks but looks like tests are failing? https://github.com/apache/tinkerpop/actions/runs/7453987383/job/20312976855?pr=2433

**Comment by xiazcy** [comment]
This needs a change in the python translator for the feature tests, which is likely why the tests are failing. https://github.com/apache/tinkerpop/blob/a7781f56be7f43fe606a24617318b30bf137d246/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/PythonTranslator.java#L206

**Comment by kenhuuu** [comment]
VOTE +1. Even though this is technically a breaking change, I'd argue it's just a bug fix since the documentation makes it sound like it should have been any_.

**Comment by Cole-Greer** [comment]
Thanks Ryan, VOTE +1

**Comment by vkagamlyk** [comment]
VOTE+1

**Pull request merged**
