### PR TITLE
TINKERPOP-1944 Export DriverRemoteConnection

### PR DESCRIPTION
**Pull request by jorgebay**
Export `DriverRemoteConnection`.

https://issues.apache.org/jira/browse/TINKERPOP-1944

VOTE +1

### CODE REVIEW

**Comment by spmallette** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by aaronjwood** [comment]
Can the docs be fixed surrounding this as well? The docs show:
```
const graph = new Graph();
const g = graph.traversal().withRemote(new DriverRemoteConnection('ws://localhost:8182/gremlin'));
```
which doesn't match up at all with what you really need to do: https://groups.google.com/d/msg/gremlin-users/YyHXS579cyw/t3TnQG_BAgAJ

The concept of importing the module and showing where to access these classes (`gremlin.driver` or `gremlin.structure` for example) is missing, which will make people have to hunt down where the classes really are.

**Comment by jbmusso** [comment]
VOTE +1

**Pull request merged**
