### PR TITLE
TINKERPOP-1552 Gremlin.Net

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1552

Presenting the Gremlin.Net GLV. It follows patterns for GLV generation established by gremlin-python and has build/deployment automation in maven. It does not have an extensive test suite given the JVM-centric nature of gremlin-test, but it does contain both unit and integration tests that should provide some confidence. 

Upgrade documentation has not been updated yet since it isn't clear if we will officially release this with 3.2.6 or not. We may just do SNAPSHOT style releases until we gather more feedback. I suspect that we will have more changes to Gremlin.Net before 3.2.6 is ready for release, but the work seems stable enough to be in a release branch at this point.

Builds with docker nicely - @dkuppitz could you please take a look at the docker changes for this? not sure if anything else needs to be done (or done differently).

VOTE +1

### CODE REVIEW

**Comment by dkuppitz** [comment]
I guess `dotnet-dev-1.0.1` could be bumped to `dotnet-dev-1.0.4` (that's currently the latest).

What is `apt-transport-http` needed for?

**Comment by FlorianHockmann** [comment]
Yes, bumping dotnet dev to 1.0.4 makes sense. 1.0.1 was probably the newest version when I worked on the Dockerfile.

> What is apt-transport-http needed for?

The .NET Core APT repos seem to only work with HTTPS. So `apt-transport-https` needs to be installed first.

**Comment by jorgebay** [comment]
Some minor nits:
 - Entries in root `.gitignore` file can be moved to `gremlin-dotnet/.gitignore` to avoid polluting the root file.
 - The coding style for generated enums is not very common, one declaration per line is expected in C#.

Apart from that, it looks good to me.

**Comment by spmallette** [comment]
Made some adjustments:

1. Bumped to `dotnet-dev-1.0.4`
2. Fixed the enums so they are on separate lines

I left `.gitignore` as gremlin-python also pollutes that space atm and I wasn't too worried about it. I guess we can tweak that up whenever if it's bugging anyone. Any votes from committers now?

**Comment by jorgebay** [comment]
I'm going to use my newly obtained committer status to say: +1!

**Comment by FlorianHockmann** [comment]
Since most of the changes in this pull request are my own and I like the work in it from @spmallette and @jorgebay, I'll also use my new committer status to VOTE +1 on this one.

**Comment by spmallette** [comment]
I will get this merged in the next day or so.

**Comment by spmallette** [comment]
sadly the merge to master didn't go cleanly - see the new PR at #670 to get this to master. there are failing tests. @FlorianHockmann could you have a look at those and see if it is easy to correct? if so, feel free to just push your changes directly to that branch - much easier to do things now that you are a committer :)  thanks.

**Pull request merged**
