### PR TITLE
TINKERPOP-1995 Return the Promise on Close

### PR DESCRIPTION
**Pull request by elliotttf**
This replaces #887.

### CODE REVIEW

**Comment by jorgebay** [comment]
Thanks for changing the base branch @elliotttf 

Looks good, VOTE +1

**Comment by spmallette** [comment]
VOTE +1

**Comment by jorgebay** [comment]
As this is a straightforward bug fix, I think its ok to do a CTR and avoid waiting for an additional review/vote.

**Comment by spmallette** [comment]
Sure - looks that way to me.  Please add a changelog entry when you merge.

**Pull request merged**
