### PR TITLE
TINKERPOP-1331 HADOOP_GREMLIN_LIBS can only point to local file system

### PR DESCRIPTION
**Pull request by dkuppitz**
https://issues.apache.org/jira/browse/TINKERPOP-1331

It's now possible to have DFS paths in `HADOOP_GREMLIN_LIBS`.

VOTE: +1

### CODE REVIEW

**Comment by spmallette** [comment]
Note that the travis integration is broken here because of the migration from incubator (i.e. the link is just broken). One job passed and one failed - here's the passing run:

https://travis-ci.org/apache/tinkerpop/builds/136484066

The failing run was due to a failure in the gremlin server tests, but i'm guessing that to be an internal failure of travis and not something related to this PR since we did get a green build out of this.

VOTE +1

**Comment by okram** [comment]
I don't see any test cases. I would like to see some tests in {{HadoopGremlinSuite}} that shows that using {{hdfs://}} and {{file://}} in {{HADOOP_GREMLIN_LIBS}} works. Also, that its backwards compatible with the {{x/y/z:a/b/c:blah/blah}} as previous.

**Comment by dkuppitz** [comment]
The failing Travis test run contains a massive amount of exceptions in `RemoteGraphProcessComputerTest` which ultimately led to:

```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

I don't think that's in any way related to my PR.

**Comment by okram** [comment]
Do the reference docs need to be updated with your new work? If so, can you update the docs in the PR too (please)?

**Comment by dkuppitz** [comment]
Added a note in `implementations-hadoop.ascidoc`.

**Comment by okram** [comment]
VOTE +1

**Pull request merged**
