### PR TITLE
Remove errant import of javafx class

### PR DESCRIPTION
**Pull request by greedy**

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for this. Could you please re-target your PR at the tp32 branch?

**Comment by spmallette** [comment]
@greedy not sure if you didn't see my earlier comment, but i can get this merged if you re-target the change to the `tp32` branch.

**Comment by greedy** [comment]
@spmallette The import doesn't exist in tp32, only master.

**Comment by spmallette** [comment]
hmm - i wonder what i was looking at. when i first asked you to change the target branch, i'd taken the time to look at tp32 to see if it applied there and i thought i saw the problem there too. ok - must have been my mistake. sorry it took a while to get this merged then. i'll do it now.

**Pull request merged**
