### PR TITLE
Reverts TINKERPOP-2289 resolve ip address

### PR DESCRIPTION
**Pull request by robertdale**
See:
1.  [User list](https://groups.google.com/d/msg/gremlin-users/A9rr9jLh5AY/DLguF9QmAQAJ)
2. [Dev list](https://lists.apache.org/thread.html/5a606bb428941faaac5c41c4df1526351406ec1ca90574dc9ced7fcd@%3Cdev.tinkerpop.apache.org%3E)

`mvn clean install`  success.

### CODE REVIEW

**Comment by spmallette** [comment]
I think revert is a good first step here. Depending upon how the dev list thread goes we can figure out if new JIRA issues are required. Aside from a CHANGELOG entry this looks good to me. 

@olivertowers if you have a moment to test this branch with CosmosDB to validate that all is good, that would be hugely helpful. if it would be helpful to have a fresh SNAPSHOT published with this change I can do that ..just let me know.  cc/ @luisbosquez

VOTE +1

**Comment by robertdale** [comment]
VOTE +!

**Comment by spmallette** [comment]
Travis was green here - restarted the "server/console" job to see if this change fixes a "new" problem of a failing test in Travis. doesn't seem to happen locally and nothing has changed of significance except for the move to xenial on Travis. if travis goes red i wouldn't let it stop this PR from merging. just grasping at straws for what might be wrong.

**Comment by spmallette** [comment]
hmm - passed - tried merging this change forward to `travis-fix` which is based on `tp34`. maybe we get a clean build now: 

https://travis-ci.org/apache/tinkerpop/builds/609643926

**Comment by spmallette** [comment]
didn't fix it 😞 🤔

**Comment by olivertowers** [comment]
@spmallette I validated that the revert fixed the issue.

**Comment by spmallette** [comment]
thanks for testing @olivertowers - i've published fresh snapshots for all release branches.

**Pull request merged**
