### PR TITLE
TINKERPOP-1665 Remove unittest from Gremlin-Python tests

### PR DESCRIPTION
**Pull request by davebshow**
A simple PR that removes unnecessary `unittest` code from the Gremlin-Python test suite. 

VOTE +1

### CODE REVIEW

**Comment by spmallette** [comment]
Do you mind also doing that here:

https://github.com/apache/tinkerpop/blob/tp32/gremlin-console/src/test/python/tests/test_console.py

**Comment by davebshow** [comment]
Didn't even know that existed. Done.

**Comment by spmallette** [comment]
It was recently added to better test the gremlin console. Thanks for cleaning that up.

All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
