### PR TITLE
TINKERPOP-2857 add GraphFilter support for GraphSONRecordReader

### PR DESCRIPTION
**Pull request by ministat**
The GraphSONRecordReader does not provide the GraphFilter to filter vetex during deserialization. This PR fixed it. In addition, two UTs for vertex filtering of both GraphSONRecordReader and GryoRecordReader were added.

### CODE REVIEW

**Comment by ministat** [comment]
retest

**Comment by Cole-Greer** [comment]
These changes look good to me. It doesn't appear that it would introduce any breaking changes to existing users.

In case you aren't already aware @ministat, we are currently in the middle of a code freeze for the upcoming releases of 3.5.5 and 3.6.2. As such I wouldn't expect much activity on this PR until after the release is completed.

**Comment by ministat** [comment]
@Cole-Greer Good to know the code freeze for new release. Thanks for notification.

**Comment by ministat** [comment]
@Cole-Greer Considering 3.6.2 is released. Could you please take a look at this PR?

**Comment by Cole-Greer** [comment]
@ministat I took another look at this and it looks good to me. Looks like a similar implementation to how `GryoRecordReader` and `ScriptRecordReader` already handle `GraphFilter`s. Unfortunately I can't give any binding votes on this as I'm not a Tinkerpop committer but I will give it a VOTE +1 (Non-Binding).

**Comment by ministat** [comment]
@Cole-Greer Thanks for your prompt response and recognition of my PR. :-)

**Pull request merged**
