### PR TITLE
TINKERPOP-1507: Pick.any and Pick.none are not in GraphSON or Gremlin-Python

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1507

`Pick.any` and `Pick.none` were not in any of the registered serialization systems -- Java or Python. Nor in the static imports. This has since been rectified and two new test cases add to `BranchTest` and `ChooseTest` to demonstrate that these tokens are now being processed correctly.

CHANGELOG

```
* Added `Pick.none` and `Pick.any` to the serializers and importers.
```

VOTE +1.

### CODE REVIEW

**Comment by spmallette** [comment]
Shouldn't this be a fix to tp32 and 3.2.x line?

**Comment by okram** [comment]
Its branched off the `tp32` line. I just fuggled the "wants to merge to." I will merge it to `tp32` come the time and upmerge to `master`.

**Comment by spmallette** [comment]
> I will merge it to tp32 come the time and upmerge to master.

enjoy that while it lasts :)

Since you added new types for GraphSON, you should update the IO Reference Documentation:

https://github.com/apache/tinkerpop/blob/42090f2e8445242bd662fed5fd9a0b255a5e46f9/docs/src/dev/io/graphson.asciidoc

I can't link directly to the part of the file to update, but basically, the comments of that file contain a groovy script which generates a portion of the graphson.asciidoc file (just cut/paste output into it). As I explain this, I realize that perhaps this process could be nicer, but it is what it is for now.

**Comment by okram** [comment]
Updated `graphson.asciidoc`.

**Comment by spmallette** [comment]
Note that the graphson.asciidoc generation isn't automatic. it's a script you have to run manually (so the content it generates isn't currently present if you were to generate docs). It can be run later i guess. Like i said, it's not a terribly automated process atm.

All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Comment by twilmes** [comment]
VOTE: +1

**Pull request merged**
