### PR TITLE
fix typo for OLTP

### PR DESCRIPTION
**Pull request by AndreasHeiberg**

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for noticing that and fixing it, but could you please re-target your pull request to the tp32 branch so that this can apply to the 3.2.x line of code. I will merge it forward to master from there.

**Comment by robertdale** [comment]
Could you also fix the ones in `docs/src/dev/provider/index.asciidoc` ?

**Comment by AndreasHeiberg** [comment]
@spmallette will do
@robertdale I did as a separate PR because that's the easiest through the Github GUI. Sorry for that :)

**Comment by AndreasHeiberg** [comment]
See #582

**Pull request closed without merging**
