### PR TITLE
TINKERPOP-1332: Improve .explain() Dialogue

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1332

`TraversalExplanation.toString()` now supports word wrapping and `GraphFilter` information.

*First, here is word wrap in action*:

```
gremlin> g.V().out().out().out().out().count().explain()
==>Traversal Explanation
=======================================================================================================================================
Original Traversal                 [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), CountGlobalStep]

ConnectiveStrategy           [D]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), CountGlobalStep]
RangeByIsCountStrategy       [O]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), CountGlobalStep]
IdentityRemovalStrategy      [O]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), CountGlobalStep]
IncidentToAdjacentStrategy   [O]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), CountGlobalStep]
AdjacentToIncidentStrategy   [O]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,edge), CountGlobalStep]
FilterRankingStrategy        [O]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,edge), CountGlobalStep]
MatchPredicateStrategy       [O]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,edge), CountGlobalStep]
TinkerGraphStepStrategy      [P]   [TinkerGraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,edge), CountGlobalStep]
ProfileStrategy              [F]   [TinkerGraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,edge), CountGlobalStep]
StandardVerificationStrategy [V]   [TinkerGraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,edge), CountGlobalStep]

Final Traversal                    [TinkerGraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,edge), CountGlobalStep]
gremlin>
```

*Second, here is GraphFilter information in action.*

```
gremlin> g = TinkerFactory.createModern().traversal().withComputer()
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], graphcomputer]
gremlin> g = g.withStrategies(GraphFilterStrategy.instance())
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], graphcomputer]
gremlin> g.V().out().out().out().out().count().explain()
==>Traversal Explanation
==========================================================================================================================================
Original Traversal                 [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), CountGlobalStep]

VertexProgramStrategy        [D]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,vertex), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
ConnectiveStrategy           [D]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,vertex), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
RangeByIsCountStrategy       [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,vertex), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
IdentityRemovalStrategy      [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,vertex), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
IncidentToAdjacentStrategy   [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,vertex), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
AdjacentToIncidentStrategy   [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
FilterRankingStrategy        [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
MatchPredicateStrategy       [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
OrderLimitStrategy           [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
PathProcessorStrategy        [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[none]),
                                      ComputerResultStep]
GraphFilterStrategy          [O]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[[VertexStep(OUT,edge)]]),
                                      ComputerResultStep]
TinkerGraphStepStrategy      [P]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[[VertexStep(OUT,edge)]]),
                                      ComputerResultStep]
ProfileStrategy              [F]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[[VertexStep(OUT,edge)]]),
                                      ComputerResultStep]
ComputerVerificationStrategy [V]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[[VertexStep(OUT,edge)]]),
                                      ComputerResultStep]
StandardVerificationStrategy [V]   [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[[VertexStep(OUT,edge)]]),
                                      ComputerResultStep]

Final Traversal                    [TraversalVertexProgramStep([GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
                                      VertexStep(OUT,vertex), VertexStep(OUT,edge), CountGlobalStep],graphfilter[[VertexStep(OUT,edge)]]),
                                      ComputerResultStep]
gremlin>
```

**PLEASE ADVISE**

Note that I have hardcoded the wordwrap amount `final int maxLineLength = 75;`. It would be nice if this was set to the console window size in some way... :/ ... any thoughts on how to make this more dynamic?

**CHANGELOG**

```
* `VertexProgramStep.toString()` contains `GraphFilter` information.
* `TraversalExplanation.toString()` supports word wrapping.
```

`mvn clean install` passed.

VOTE +1.

cc/ @rjbriody @RussellSpitzer

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
I still think this is pretty verbose, but I'm happy with the inclusion of the 
```graphfilter[[VertexStep(OUT,edge)]]``` so +1 on that

**Comment by spmallette** [comment]
Note that there are comments on this PR in the JIRA ticket itself.

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by okram** [comment]
Can someone else VOTE on this please?

**Comment by PommeVerte** [comment]
Jline should have some support for obtaining terminal width though it might not be all that reliable : 
```java
jline.TerminalFactory.get().getWidth();
```
I think the above might fail in some instances such as resizing the window after launching the app, or if the users are using a shell that doesn't support some column global envs. So falling back to 75 might be a good approach if the above doesn't return a width.

This looks good. VOTE +1

**Comment by okram** [comment]
Note that there is a fall back if the `getWidth()` is "too small" ... people say when it fails, it returns -1 so the fall back will kick in.

**Comment by PommeVerte** [comment]
duh I totally missed that line when looking through the changes. Late to the party >.<

**Pull request merged**
