### PR TITLE
Reuse a byte buffer instead of re-allocating it on every loop.

### PR DESCRIPTION
**Pull request by danielcweber**
For large result sets, this will release a little bit of GC pressure.

### CODE REVIEW

**Comment by danielcweber** [comment]
Failing test is unrelated and already failing on master.

**Comment by danielcweber** [comment]
Seems that the data received from the test gremlin server got some extra fields (gremlin.pageRankVertexProgram.pageRank, gremlin.pageRankVertexProgram.edgeCount)

Expected: Dictionary<String, IList<Object>> [[age, System.Collections.Generic.List`1[System.Object]], [name, System.Collections.Generic.List`1[System.Object]]]
Actual:   Dictionary<String, IList<Object>> [[name, System.Collections.Generic.List`1[System.Object]], [age, System.Collections.Generic.List`1[System.Object]], [gremlin.pageRankVertexProgram.pageRank, System.Collections.Generic.List`1[System.Object]], [gremlin.pageRankVertexProgram.edgeCount, System.Collections.Generic.List`1[System.Object]]]

**Comment by spmallette** [comment]
Is this meant for `master` branch? should it target something earlier?

**Comment by danielcweber** [comment]
It's not fixing a bug or something urgent. Not sure what the criteria should be for it to target something earlier.

**Comment by FlorianHockmann** [comment]
Our policy is to target the lowest still active release branch possible. We'll then merge a PR into that branch and afterwards merge that release branch into higher release branches and ultimately master. That way, a fix lands in all possible release branches.
In your case, `3.3-dev` should be the correct release branch as it already contains that code and because we stopped working on the `3.2-dev` branch.
@spmallette: Should we maybe rename the inactive release branches (`3.0-dev` - `3.2-dev`) to avoid confusion?

**Comment by danielcweber** [comment]
Rebased, base branch changed to 3.3-dev.

**Comment by spmallette** [comment]
> Should we maybe rename the inactive release branches (3.0-dev - 3.2-dev) to avoid confusion?

i'd say that most of the time, the problem is folks heading straight to `master` with their PR rather than to an older dev branch so i'm not sure we have a problem with inactive branches at this point. imo, i'd just leave them named as they are until we have a consistent problem with it.

**Pull request merged**
