### PR TITLE
TINKERPOP-2530: Transfer OyvindSabo/gremlint and OyvindSabo/gremlint.com to apache/tinkerpop/gremlint

### PR DESCRIPTION
**Pull request by OyvindSabo**
https://issues.apache.org/jira/browse/TINKERPOP-2530

Transfers [OyvindSabo/gremlint](https://github.com/OyvindSabo/gremlint) and [OyvindSabo/gremlint.com](https://github.com/OyvindSabo/gremlint.com) to `tinkerpop/gremlint/` and `tinkerpop/docs/site/home/gremlint`, respectively. This is the first step of the steps outlined [here](https://lists.apache.org/x/thread.html/r39f1293250df2a1f679ed6687914416dc9527cbce663e5723b68e60e@%3Cdev.tinkerpop.apache.org%3E) for bringing the Gremlint code recently donated by Ardoq into TinkerPop.

`gremlint.com` still installs `gremlint` from `github:OyvindSabo/gremlint#master` since I haven't yet found a way to install a package from a git subdirectory using npm. I've left this unchanged until we make `gremlint` available on npm.

### CODE REVIEW

**Comment by spmallette** [comment]
A first thing to consider is that this change breaks the build as the RAT plugin which checks for files without appropriate license headers is complaining:

> [ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (rat-checks) on project tinkerpop: Too many files with unapproved license: 14 See RAT report in: /home/travis/build/apache/tinkerpop/target/rat.txt -> [Help 1]

Could you please try to fix that? There are two approaches:

1. We err on the side of caution and generally just add the license header to everything, even, html/css files for our website
2. If for some reason you can't do (1) then you add an exclusion to RAT [here](https://github.com/apache/tinkerpop/blob/4aed59437b0f122cc68c875bd7eb5b55443f7ea8/pom.xml#L370-L425).

> Any thoughts on this folder structure?
> Do we want to include the gremlint website code here at all or should it reside elsewhere?

We keep all of our "website" things in `docs/site`. We then have a [script](https://github.com/apache/tinkerpop/blob/4aed59437b0f122cc68c875bd7eb5b55443f7ea8/bin/publish-home.sh) that publishes the contents of `site/home` along with generated documentation to Apache infrastructure. That is done with SVN. In that sense, I feel as though gremlint.com should find a home there so that "website" things sorta stay together. On that note, perhaps my thinking would be more clear if we knew how gremlin.com will exist on Apache infrastructure. As you'd said that you would be the person handling the domain transfer, perhaps you could start that process and begin a discussion with Apache about how we would host gremlint.com? All you need to do is [create a JIRA for Infra](https://issues.apache.org/jira/projects/INFRA/) to get that process started - here is an [example](https://issues.apache.org/jira/browse/INFRA-18792). You should likely reference the [VOTE thread](https://lists.apache.org/thread.html/r1006ed56b5d92628f3378f9baef854da6fef3f83d8492b746b467ab6%40%3Cdev.tinkerpop.apache.org%3E) we had. Once you get that created, please add the Infra JIRA to TINKERPOP-2530 for reference.

I think we need to know how we would publish to gremlint.com once the transfer is done. I presume it would be in the same fashion as we currently do for our home page/docs. I suppose another option would be for gremlint to live at `http://tinkerpop.apache.org/gremlint` and then redirect to that from gremlin.com. Not sure what they would prefer for something like this. In any case, the JIRA will get that conversation going.

> Would something like apache/tinkerpop/gremlint/lib and apache/tinkerpop/gremlint/website be preferable?

perhaps. i've envisioned gremlint as something we publish to npm so that it can get used as a library. as such, it will need to fall under the general Maven build structure. If that is the case, then the "lib" will have to look more like the structure in `gremlin-javascript` - you might want to take a look at that modulate to see how it is setup. I don't think we need to make a final choice on this until we hear a bit from Apache Infra. 

> Some files, like the README.md and package.json files have links to OyvindSabo/gremlint and OyvindSabo/gremlint.com. Also, gremlint.com still installs gremlint from github:OyvindSabo/gremlint#master. I haven't made changes to any of this for now. Would it be preferable to do that in this PR or can it be done in a follow-up PR?

My suggestion would be that you keep this initial commit, which is the "base transfer" and simply push additional commits to this branch on top of it as we learn more from Infra. Therefore, feel free to push additional commits to deal with the README/package.json/etc. Another little addition to make would be to introduce gremlint in our Upgrade Documentation. You can make an entry for that [here](https://github.com/apache/tinkerpop/blob/master/docs/src/upgrade/release-3.5.x.asciidoc#upgrading-for-users). In the Upgrade Docs we call out major new features and changes so that users can get a feel for what's "new" after we release. If you'd like to draft something there, that would be good. 

Finally, almost no PR is "complete" without a CHANGELOG [entry](https://github.com/apache/tinkerpop/blob/4aed59437b0f122cc68c875bd7eb5b55443f7ea8/CHANGELOG.asciidoc) - even though we pull in JIRAs and their descriptions on release, we sometimes do work that is outside of JIRA or work that requires more subtle description or greater summary than a JIRA title, so we always just add a entry to CHANGELOG.

**Comment by OyvindSabo** [comment]
I fixed the `apache-rat-plugin` warnings so now the tests pass. I agree with the idea of having gremlint as a library which will be published to npm with a similar structure to `gremlin-javascript`, and have gremlint.com together with other website things. I'll try to have the Jira ticket for Infra out tomorrow, so get some input from them:+1:

**Comment by OyvindSabo** [comment]
From the [Apache Infra discussion](https://issues.apache.org/jira/browse/INFRA-21547) I understood that it would be fine to work with the assumption that the gremlint web page code will not be located within the `tinkerpop/gremlint` folder.

I'll update this PR to place just the gremlint library code in `tinkerpop/gremlint`, rather than placing the library code under `tinkerpop/gremlint/gremlint` and the wep page code under `tinkerpop/gremlint/gremlint.com` as I've done currently.

That way I can more easily start looking into how the library would be included in the Maven build structure, without doing a lot of temporary work which will need to change upon a future folder structure change. It will also let me remove some `apache-rat-plugin` entries in `pom.xml` I added for gremlint.com files in which I could not put an Apache license.

Question: When adding the gremlint.com code to this PR I made some updates like adding a few missing license headers and some README mistakes I noticed. Would it be okay to push those changes to the `OyvindSabo/gremlint.com` repository before it gets transferred to Apache, or does the latest commit hash have to match the one in the gremlint IP Clearance document? If so, would it be cumbersome to update those at this point?

**Comment by spmallette** [comment]
> I'll update this PR to place just the gremlint library code in tinkerpop/gremlint, rather than placing the library code under tinkerpop/gremlint/gremlint and the wep page code under tinkerpop/gremlint/gremlint.com as I've done currently.

yeah - i think that makes sense. ultimately i think we'll push the gremlint.com stuff to a directory here given that discussion with infra: 

https://github.com/apache/tinkerpop/tree/master/docs/site/home

> That way I can more easily start looking into how the library would be included in the Maven build structure, without doing a lot of temporary work which will need to change upon a future folder structure change. It will also let me remove some apache-rat-plugin entries in pom.xml I added for gremlint.com files in which I could not put an Apache license.

I'd like to see this PR get merged in time for 3.5.0 which i would like to see release in April. For 3.5.0 it would be enough for me to see the code in the repo and http://tinkerpop.apache.org/gremlint (or whatever it is) active. Perhaps we just focus on that much for this initial PR and then you can do additional maven build structure related work at a later point after it's merged. If that work makes it to 3.5.0, great! if not, no worries/no pressure. does that make sense to you?

> Question: When adding the gremlint.com code to this PR I made some updates like adding a few missing license headers and some README mistakes I noticed. Would it be okay to push those changes to the OyvindSabo/gremlint.com repository before it gets transferred to Apache, or does the latest commit hash have to match the one in the gremlint IP Clearance document? If so, would it be cumbersome to update those at this point?

I'm not sure about the hash to be honest. Let's try to keep the initial commit aligned to what was in the IP Clearance document. Feel free to just move things around as needed in this PR.  If we don't like the extended commit history we can just squash everything down to two commits before merge, your initial one and then your changes that came afterwords. As this is all new code it shouldn't create merge conflicts or any hassles to worry about that I can think of. sound good?

**Comment by OyvindSabo** [comment]
> For 3.5.0 it would be enough for me to see the code in the repo and http://tinkerpop.apache.org/gremlint (or whatever it is) active. Perhaps we just focus on that much for this initial PR and then you can do additional maven build structure related work at a later point after it's merged. If that work makes it to 3.5.0, great! if not, no worries/no pressure. does that make sense to you?

Yes, if that's good by you as a starting point I'm all for that:+1:

**Comment by spmallette** [comment]
i re-read what I wrote and just to be clear, when i said:

> Perhaps we just focus on that much for this initial PR and then you can do additional maven build structure related work at a later point after it's merged. If that work makes it to 3.5.0, great! if not, no worries/no pressure.

I meant that the "optional" part in my mind for 3.5.0 was the maven automation. If that work makes it in then great and if not no worries. We can even save publishing a gremlint artifact to npm for another version. That's no rush in my mind. For 3.5.0, let's just get gremlint code to `tinkerpop/gremlint` and the website code to `tinkerpop/docs/site/home/gremlint`. In the latter case, I think that if that `/gremlint` directory is present there the script that publishes the website might actually just pick that up and publish it to https://tinkerpop.apache.org/gremlint 

Perhaps you understood what I wrote earlier as that already but I just wanted to be sure. 🙂

**Comment by OyvindSabo** [comment]
Yes, that's how I understood it:+1: I'll update the file structure after work today:slightly_smiling_face:

**Comment by OyvindSabo** [comment]
As of today I believe all the suggested changes so far have been implemented, so here is a summary of what has been done:

- The code from `OyvindSabo/gremlint` has been placed in `apache/tinkerpop/gremlint`.

- The code from `OyvindSabo/gremlint.com` has been placed in `apache/tinkerpop/docs/site/home/gremlint`.

- Some files in the transferred code were missing an ASF licence header. I've added the missing headers where possible and excluded the remaining from `apache-rat-plugin` in `pom.xml`, so all tests pass.

- Some places in the transferred code there were links that linked back to the OyvindSabo/gremlint and OyvindSabo/gremlint.com repositories. Those have been updated to link to TinkerPop equivalents.

- I've written drafts for the CHANGELOG (b9115e3) and Upgrade documentation (a1d8af8). Seeing as this code transfer is a bit different from previous changelog and upgrade documentation entries I'm not really sure how it would be customary to do this, so suggestions for improvement are welcome!

- The PR does not add gremlint in the Maven build structure and does not publish it to npm. As discussed, those can be done in follow-up PRs once the basic code transfer is done.

**Comment by spmallette** [comment]
As I've looked at this in a final bit of detail now, I think I've misunderstood gremlint.com a bit and I've misled you slightly. My misunderstanding comes from my ignorance of react based sites. As i follow it now, gremlint.com needs to be generated to a static site (which wasn't obvious to me up until now believe it or not 😳 ). If we keep it at `docs/site/home/gremlint` it will get published without that generation basically as source code. I'm sorry to ask you to move it again, but it really should exist at `docs/gremlint` and then we will modify our standard site publish scripts (separate from this PR) to run the `npm run build` and push the static site up to `https://tinkerpop.apache.org/gremlint`

i'm really sorry i misunderstood. i should have looked at it more closely earlier. if you do that final change, i would say you should feel free to merge this PR to `master`: VOTE +1

**Comment by OyvindSabo** [comment]
No worries:) I moved the folder now and also studied the TinkerPop site generating scripts a bit closer, so now I have a better understanding of how the current website stuff works. I'll merge the PR later today. From the TinkerPop developer documentation I understand that merging is basically just pressing the "Merge pull request" button without having to bother with squashing or rebasing unless necessary to avoid conflicts?

VOTE +1

**Comment by spmallette** [comment]
>  studied the TinkerPop site generating scripts a bit closer, so now I have a better understanding of how the current website stuff works. 

yes, it's just `bin/generate-home.sh` and `bin/publish-home.sh`.  I've created https://issues.apache.org/jira/browse/TINKERPOP-2544 with some initial thoughts on what's involved. It should be easy enough. Once that piece is ready to go (again, on a separate PR), I will immediately publish the site with gremlint and we can (1) promote the work and (2) finish up with apache infra.

> From the TinkerPop developer documentation I understand that merging is basically just pressing the "Merge pull request" button without having to bother with squashing or rebasing unless necessary to avoid conflicts?

In other cases, we'd prefer a clean commit history and encourage squashing where it makes sense, but in this case, I'd say, lets keep all of the history we've constructed as it shows the progression from the initial IP clearance. Since you're pointed at `master` with no conflics the "Merge pull request" button will suffice in this case.

**Pull request merged**
