### PR TITLE
TINKERPOP-1254 Support dropping traverser path information when it is no longer needed

### PR DESCRIPTION
**Pull request by twilmes**
This PR adds support for path retraction to increase the likelihood of bulking in OLTP and OLAP modes. Traversal analysis is performed during the application of the PrunePathStrategy to identify labels that may be dropped at various points in the traversal.  MatchStep also performs runtime analysis to determine which labels it can drop in addition to the labels identified during traversal strategy application.

Here is a set of profiles showing the benefit of path dropping.  These were generated with `TinkerGraphComputer` first against 3.2 and then TinkerPop-1254.  **Note** that the times should not be compared here.  The first was run on my anemic macbook which, and the second was run on an 8 core AWS m3.2xlarge instance that I've been using for testing.  I'll be following up with more numbers on the same hardware but you can see here the dramatic drop in traversers with path pruning enabled.

**TP 3.2**
```
gremlin> g.V().match(__.as('a').out().as('b'), __.as('b').out().as('c'), __.as('c').out().as('d')).select('d').count().profile()
==>Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
TinkerGraphStep(vertex,[])                                           808         808          21.205     0.02
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...              14465066    14465066      110317.813    85.88
  MatchStartStep(a)                                                  808         808       10975.797
  VertexStep(OUT,vertex)                                            8049        8049        6953.071
  MatchEndStep(b)                                                   8049        8049        6727.167
  MatchStartStep(b)                                                 8049        7957        5461.242
  VertexStep(OUT,vertex)                                          327370      327370        6782.024
  MatchEndStep(c)                                                 327370      327370        6238.268
  MatchStartStep(c)                                               327370      326983        1771.773
  VertexStep(OUT,vertex)                                        14465066    14465066       11489.228
  MatchEndStep(d)                                               14465066    14465066       14301.313
SelectOneStep(d)                                                14465066    14465066       13752.966    10.71
CountGlobalStep                                                        1           1        4363.667     3.40
                                            >TOTAL                     -           -      128455.652        -
```
 **TinkerPop-1254**
```
gremlin> g.V().match(__.as('a').out().as('b'), __.as('b').out().as('c'), __.as('c').out().as('d')).select('d').count().profile()
==>Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
GraphStep(vertex,[])                                                 808         808          32.453    19.96
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...              14465066        7510          89.463    55.01
  MatchStartStep(a)                                                  808         808          22.388
  VertexStep(OUT,vertex)                                            8049        7957          85.493
  MatchEndStep(b) (profiling ignored)                                                          0.000
  MatchStartStep(b)                                                 8049         563           7.488
  VertexStep(OUT,vertex)                                          327370        7561          19.548
  MatchEndStep(c) (profiling ignored)                                                          0.000
  MatchStartStep(c)                                               327370         452           4.247
  VertexStep(OUT,vertex)                                        14465066        7510          14.812
  MatchEndStep(d) (profiling ignored)                                                          0.000
SelectOneStep(d)                                                14465066         452          40.711    25.03
CountGlobalStep                                                        1           1           0.001     0.00
                                            >TOTAL                     -           -         162.630        -
```

One thing that I did want to call out.  I was seeing some strange errors in the `MutablePath.retract` method that I traced to multiple threads attempting to do a retract at the same time.  I did not think this should happen or would be possible but I may be misunderstanding how `GraphComputer` executes.  To fix this, I added a `synchronized` block.  I was hesitant to do this but it fixed the problem and appears to have not slowed things down appreciably.  There may be a better way around this though so any input would be welcome.

Tests pass and I got a passing integration test last night but made a few changes since then.  I'll follow up with new integration test results when they finish running today.

VOTE: +1

### CODE REVIEW

**Comment by dkuppitz** [comment]
`docker/build.sh -t -i -n` fails with:

```
Failed tests: 
  DedupTest$Traversals>DedupTest.g_V_both_name_order_byXa_bX_dedup_value:110 expected:<[josh]> but was:<[marko]>
```

**Comment by twilmes** [comment]
I made a small update to `ReferencePath` to create new label Sets when a patch is detached.  This had been causing issues where the first set of labels for a path where being shared across `MutablePaths` after detachment.  A label would be removed from one, and therefore all of the traversers that had that label `Set` in their path, would be affected.

The `PathProcessors` are now respecting keepLabels null and labels are not dropped if `PrunePathStrategy` is not applied.

**PrunePathStrategy on**
```
g.V().match(
    as("a").in("sungBy").as("b"),
    as("a").in("sungBy").as("c"),
    as("b").out("writtenBy").as("d"),
    as("c").out("writtenBy").as("e"),
    as("d").has("name", "George_Harrison"),
    as("e").has("name", "Bob_Marley")).select("a").count().profile()

Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
GraphStep(vertex,[])                                                 808         808          44.217    99.97
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...                     1           1           0.004     0.01
  MatchStartStep(a)                                                  808         808          43.517
  VertexStep(IN,[sungBy],vertex)                                     501         499          20.323
  MatchEndStep(b) (profiling ignored)                                                          0.000
  MatchStartStep(a)                                                    2           2           0.006
  VertexStep(IN,[sungBy],vertex)                                     156         156           2.129
  MatchEndStep(c) (profiling ignored)                                                          0.000
  MatchStartStep(b)                                                  501         499           5.126
  VertexStep(OUT,[writtenBy],vertex)                                 509         504           3.423
  MatchEndStep(d) (profiling ignored)                                                          0.000
  MatchStartStep(c)                                                  156         156           1.083
  VertexStep(OUT,[writtenBy],vertex)                                 157         157           1.029
  MatchEndStep(e) (profiling ignored)                                                          0.000
  MatchStartStep(d)                                                  509         266           1.685
  HasStep([name.eq(George_Harrison)])                                  2           2           0.002
  MatchEndStep (profiling ignored)                                                             0.000
  MatchStartStep(e)                                                  157          57           0.391
  HasStep([name.eq(Bob_Marley)])                                       1           1           0.001
  MatchEndStep (profiling ignored)                                                             0.000
SelectOneStep(a)                                                       1           1           0.003     0.01
CountGlobalStep                                                        1           1           0.003     0.01
                                            >TOTAL                     -           -          44.228        -
```
**PrunePathStrategy off**
```
Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
GraphStep(vertex,[])                                                 808         808           7.565    99.84
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...                     1           1           0.007     0.10
  MatchStartStep(a)                                                  808         808           5.726
  VertexStep(IN,[sungBy],vertex)                                     501         499           9.532
  MatchEndStep(b) (profiling ignored)                                                          0.000
  MatchStartStep(a)                                                    2           2           0.007
  VertexStep(IN,[sungBy],vertex)                                     156         156           1.803
  MatchEndStep(c) (profiling ignored)                                                          0.000
  MatchStartStep(b)                                                  501         499           3.221
  VertexStep(OUT,[writtenBy],vertex)                                 509         504           2.297
  MatchEndStep(d) (profiling ignored)                                                          0.000
  MatchStartStep(c)                                                  156         156           1.192
  VertexStep(OUT,[writtenBy],vertex)                                 157         157           0.910
  MatchEndStep(e) (profiling ignored)                                                          0.000
  MatchStartStep(d)                                                  509         504           1.533
  HasStep([name.eq(George_Harrison)])                                  2           2           0.002
  MatchEndStep (profiling ignored)                                                             0.000
  MatchStartStep(e)                                                  157         157           1.425
  HasStep([name.eq(Bob_Marley)])                                       1           1           0.000
  MatchEndStep (profiling ignored)                                                             0.000
SelectOneStep(a)                                                       1           1           0.003     0.04
CountGlobalStep                                                        1           1           0.001     0.02
                                            >TOTAL                     -           -           7.577        -
```

I am running the integration tests now and will respond back when they complete.

**Comment by twilmes** [comment]
It looks like this failed:

`IdentityRemovalStrategyTest$PerformanceTest>TraversalStrategyPerformanceTest.shouldBeFaster:107 null`

I've seen this fail on occasion in the past off of a clean master, it may be sensitive to any performance hiccups on the box that occur while the test is running.

**Comment by okram** [comment]
Verified the following simply traversal on Grateful Dead graph. For OLTP (`MatchStep.standardAlgorithm()`), I added a lazy barrier internal to `MatchStep` which is similar in behavior to the lazy barrier OLTP optimization added in `PrunePathStrategy`.

```
source.V().match(
    as("a").out().as("b"),
    as("b").out().as("c")).
  select("c").count().profile()
```

*With and then without PrunePathStrategy OLAP*

```
Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
GraphStep(vertex,[])                                                 808         808          40.418    43.47
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...                327370         452          28.015    30.13
  MatchStartStep(a)                                                  808         808          61.751
  VertexStep(OUT,vertex)                                            8049        7957          37.971
  MatchEndStep(b) (profiling ignored)                                                          0.000
  MatchStartStep(b)                                                 8049         562          14.453
  VertexStep(OUT,vertex)                                          327370        7510          16.124
  MatchEndStep(c) (profiling ignored)                                                          0.000
SelectOneStep(c)                                                  327370         452          24.531    26.39
CountGlobalStep                                                        1           1           0.004     0.00
                                            >TOTAL                     -           -          92.969        -
Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
GraphStep(vertex,[])                                                 808         808           6.844     0.35
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...                327370      326983        1257.050    64.22
  MatchStartStep(a)                                                  808         808          11.806
  VertexStep(OUT,vertex)                                            8049        7957          30.286
  MatchEndStep(b) (profiling ignored)                                                          0.000
  MatchStartStep(b)                                                 8049        7957          14.627
  VertexStep(OUT,vertex)                                          327370      326983         774.934
  MatchEndStep(c) (profiling ignored)                                                          0.000
SelectOneStep(c)                                                  327370      326983         693.564    35.43
CountGlobalStep                                                        1           1           0.001     0.00
                                            >TOTAL                     -           -        1957.460        -
```

*With and then without PrunePathStrategy OLTP*

```
Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
TinkerGraphStep(vertex,[])                                           808         808           2.050     0.07
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...                327370       56814        2794.288    91.47
  MatchStartStep(a)                                                  808         808         103.524
  VertexStep(OUT,vertex)                                            8049        8049         107.345
  MatchEndStep(b)                                                   8049        8049         159.505
  MatchStartStep(b)                                                 8049        7957         105.127
  VertexStep(OUT,vertex)                                          327370      327370         351.935
  MatchEndStep(c)                                                 327370      327370        1331.478
NoOpBarrierStep(1000)                                             327370         452         254.309     8.32
SelectOneStep(c)                                                  327370         452           3.731     0.12
CountGlobalStep                                                        1           1           0.465     0.02
                                            >TOTAL                     -           -        3054.845        -

Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
TinkerGraphStep(vertex,[])                                           808         808        2023.710    36.87
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...                327370      326983        2995.219    54.57
  MatchStartStep(a)                                                  808         808         221.105
  VertexStep(OUT,vertex)                                            8049        8049         185.946
  MatchEndStep(b)                                                   8049        8049         186.814
  MatchStartStep(b)                                                 8049        7957         161.012
  VertexStep(OUT,vertex)                                          327370      327370         405.787
  MatchEndStep(c)                                                 327370      327370         423.213
SelectOneStep(c)                                                  327370      326983         324.356     5.91
CountGlobalStep                                                        1           1         145.952     2.66
                                            >TOTAL                     -           -        5489.238        -
```

**Comment by okram** [comment]
Check this out on OLTP now....INSANE.

```
Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
TinkerGraphStep(vertex,[])                                           808         808           1.273     0.02
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...              14465066      114964        5945.246    97.59
  MatchStartStep(a)                                                  808         808          74.614
  VertexStep(OUT,vertex)                                            8049        8049          77.965
  MatchEndStep(b)                                                   8049        8049          97.455
  MatchStartStep(b)                                                 8049        7957          69.525
  VertexStep(OUT,vertex)                                          327370      327370         180.215
  MatchEndStep(c)                                                 327370      327370         792.902
  MatchStartStep(c)                                               327370       56814          98.793
  VertexStep(OUT,vertex)                                        14465066     1728961         703.308
  MatchEndStep(d)                                               14465066     1728961        2470.109
NoOpBarrierStep(2500)                                           14465066         452         144.282     2.37
SelectOneStep(d)                                                14465066         452           1.067     0.02
CountGlobalStep                                                        1           1           0.223     0.00
                                            >TOTAL                     -           -        6092.093        -

Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
TinkerGraphStep(vertex,[])                                           808         808          22.107     0.03
MatchStep(AND,[[MatchStartStep(a), ProfileStep,...              14465066    14448765       69090.223    87.45
  MatchStartStep(a)                                                  808         808        4040.859
  VertexStep(OUT,vertex)                                            8049        8049        3886.808
  MatchEndStep(b)                                                   8049        8049        3655.827
  MatchStartStep(b)                                                 8049        7957        3062.039
  VertexStep(OUT,vertex)                                          327370      327370        3942.711
  MatchEndStep(c)                                                 327370      327370        3789.122
  MatchStartStep(c)                                               327370      326983         437.946
  VertexStep(OUT,vertex)                                        14465066    14465066        5516.906
  MatchEndStep(d)                                               14465066    14465066        6793.385
SelectOneStep(d)                                                14465066    14448765        7155.383     9.06
CountGlobalStep                                                        1           1        2734.799     3.46
                                            >TOTAL                     -           -       79002.514        -
```

**Comment by twilmes** [comment]
That's excellent!  Integration tests almost ran all the way through for me, got an odd failure during the Archetype - Server, noted below.  I'm going to rerun anyway with the latest commit and using docker this time.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop ................................... SUCCESS [  9.540 s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................. SUCCESS [  3.640 s]
[INFO] Apache TinkerPop :: Gremlin Core ................... SUCCESS [01:27 min]
[INFO] Apache TinkerPop :: Gremlin Test ................... SUCCESS [ 11.518 s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................. SUCCESS [ 49.133 s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ............ SUCCESS [  8.280 s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ............ SUCCESS [03:40 min]
[INFO] Apache TinkerPop :: Gremlin Benchmark .............. SUCCESS [  4.660 s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................. SUCCESS [06:14 min]
[INFO] Apache TinkerPop :: Spark Gremlin .................. SUCCESS [19:37 min]
[INFO] Apache TinkerPop :: Giraph Gremlin ................. SUCCESS [  02:54 h]
[INFO] Apache TinkerPop :: Neo4j Gremlin .................. SUCCESS [  4.160 s]
[INFO] Apache TinkerPop :: Gremlin Driver ................. SUCCESS [ 11.340 s]
[INFO] Apache TinkerPop :: Gremlin Server ................. SUCCESS [12:58 min]
[INFO] Apache TinkerPop :: Gremlin Console ................ SUCCESS [01:36 min]
[INFO] Apache TinkerPop :: Gremlin Archetype .............. SUCCESS [  0.151 s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ........ FAILURE [  0.374 s]
[INFO] Apache TinkerPop :: Archetype - Server ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:41 h
[INFO] Finished at: 2016-07-10T15:06:49-05:00
[INFO] Final Memory: 66M/727M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project gremlin-archetype-tinkergraph: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: There was an error in the forke
d process
[ERROR] java.lang.NoClassDefFoundError: projects/standard/project/gremlin-archetype-tinkergraph/target/test-classes/com/test/example/AppTest (wrong name: com/test/example/AppTest)
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

**Comment by okram** [comment]
VOTE +1

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:44 h
[INFO] Finished at: 2016-07-10T19:35:45-06:00
[INFO] Final Memory: 113M/1585M
[INFO] ------------------------------------------------------------------------
```

**Comment by dkuppitz** [comment]
`docker/build.sh -t -i -n` succeeded (the latest 2 commits were not included).

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:43:44.864s
[INFO] Finished at: Mon Jul 11 16:59:26 UTC 2016
[INFO] Final Memory: 98M/543M
[INFO] -----------------------------------------------------------------------
```

VOTE: +1

I'll naively assume that the 2 latest commits didn't break anything.

As an aside: I think we a) shouldn't have PR's for work in progress or b) clearly communicate that the PR is not yet ready for testing. The 4-6 hours for a full test run are pretty much wasted if someone keeps adding more and more changes.

**Pull request merged**
