### PR TITLE
Re-enable certain tests and add fixes.

### PR DESCRIPTION
**Pull request by kenhuuu**
This PR re-enables and fixes certain tests that were disabled earlier because the driver and server didn't work together yet. There are still several tests that need to be re-enabled after this (some still aren't working).

### CODE REVIEW

**Comment by kenhuuu** [comment]
This PR also removes tests that involve session-based script tests as Sessions are being removed, although a recent post was made to clarify this so wait until consensus is reached [there](https://lists.apache.org/thread/9050kwfzbobfbos78wc75d5dz5mmbjzg)

**Review by vkagamlyk — APPROVED** [review]
VOTE +1

**Comment by xiazcy** [comment]
VOTE +1

**Comment by Cole-Greer** [comment]
Thanks @kenhuuu, I looked through the changes in the parts of the codebase I'm most familiar with, and it looks like good progress.
VOTE +1

**Pull request merged**
