### PR TITLE
Force startedIterating before sleep

### PR DESCRIPTION
**Pull request by BrynCooke**

### CODE REVIEW

**Comment by dkuppitz** [comment]
`AtomicBoolean first` is now no longer needed, is it?

**Comment by BrynCooke** [comment]
@dkuppitz Yes you are right, I've tweaked the PR.

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
VOTE +1

**Comment by okram** [comment]
VOTE +1.

**Pull request merged**
