### PR TITLE
Neo4j upgrade to 3.2.2 - TINKERPOP-1692

### PR DESCRIPTION
**Pull request by jexp**
for review

couldn't get the maven enforcer plugin to work
fixed two tests with Cypher syntax issues
the schema-index-performance test is flaky

see: https://github.com/neo4j-contrib/neo4j-tinkerpop-api-impl/commits/3.2

### CODE REVIEW

**Comment by robertdale** [comment]
@jexp Can you change the title to reference [TINKERPOP-1692](https://issues.apache.org/jira/browse/TINKERPOP-1692) ?

**Comment by jexp** [comment]
@robertdale done

**Comment by spmallette** [comment]
@robertdale are you looking into the issues with this PR?

**Comment by spmallette** [comment]
I made some quick/minor modifications on #680 - review/votes will occur over there. This PR will be closed. Thanks @jexp for this body of work.

**Comment by robertdale** [comment]
@jexp This PR can be closed. Thanks!

**Pull request closed without merging**
