### PR TITLE
TINKERPOP-1733 Support g.E().properties().hasKey('xx') & hasValue('xx')

### PR DESCRIPTION
**Pull request by javeme**
https://issues.apache.org/jira/browse/TINKERPOP-2313
https://issues.apache.org/jira/browse/TINKERPOP-1733

Currently, an exception will be thrown for this query: `XxProperty cannot be cast to Element`

### CODE REVIEW

**Comment by javeme** [comment]
It seems there is no effect on HadoopProperty dedup:
```java
[INFO] Running org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputerProcessIntegrateTest
[ERROR] org.apache.tinkerpop.gremlin.process.AbstractGremlinProcessTest - Expected results: [0.2]
[ERROR] org.apache.tinkerpop.gremlin.process.AbstractGremlinProcessTest - Actual results:   [0.2, 0.2]
[ERROR] org.apache.tinkerpop.gremlin.process.AbstractGremlinProcessTest - Expected results: [0.5, 0.4, 1.0, 0.2, 0.4, 1.0]
[ERROR] org.apache.tinkerpop.gremlin.process.AbstractGremlinProcessTest - Actual results:   [0.5, 0.5, 0.4, 0.4, 0.4, 0.4, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
[ERROR] Tests run: 743, Failures: 2, Errors: 0, Skipped: 175, Time elapsed: 859.733 s <<< FAILURE! - in org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputerProcessIntegrateTest
[ERROR] g_V_bothE_properties_dedup_hasKeyXweightX_hasValueXltX0d3XX_value(org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest$Traversals)  Time elapsed: 0.584 s  <<< FAILURE!
java.lang.AssertionError: Checking result size expected:<1> but was:<2>
[ERROR] g_V_bothE_properties_dedup_hasKeyXweightX_value(org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest$Traversals)  Time elapsed: 0.33 s  <<< FAILURE!
java.lang.AssertionError: Checking result size expected:<6> but was:<12>
```

**Comment by javeme** [comment]
> It seems there is no effect on HadoopProperty dedup:

According to the implementation of Property comparison, in addition to comparing to the key and value, the parent element is also compared:
```java
ElementHelper.areEqual(final Property a, final Object b) {
    return a.key().equals(((Property) b).key()) && a.value().equals(((Property) b).value()) && areEqual(a.element(), ((Property) b).element());
}
```

For StarOutEdge and StarInEdge, the same edges with two directions are not equal.
For TinkerEdge the same edges with two directions are equal.

**Comment by javeme** [comment]
hi @spmallette Could you accept this change?
And do you think it is necessary to unify the behavior of edges comparison? like StarEdge and TinkerEdge.

**Comment by spmallette** [comment]
thanks for submitting this. it may take some time to get it reviewed as we're trying to get to the bottom of a problem with instability in the Travis builds. I don't think we'll be merging too many more PRs without Travis going green again. 

as a side note, there might be an open JIRA already for this issue where there was more discussion on the topic for how to treat it. i'll eventually have to dig around for that and see what was decided.

hopefully, we'll figure out travis problems soon...thanks for your patience.

**Comment by spmallette** [comment]
we're still having issues with Travis, but I thought I'd give some basic feedback on this pull request you've submitted. first note that we already have a JIRA issue for this here:

https://issues.apache.org/jira/browse/TINKERPOP-1733

We should probably close yours as a "duplicate" and re-reference this PR to that issue. 

As an administrative note, if this capability can be safely targetted at the `tp34` branch without breaking changes I think that would be a nice feature to have along our current 3.4.x release line (if it stays on `master` it won't be available for a while.

@dkuppitz I assume you like where this PR is going. if we make `hasKey()` behave uniformly for `Element` and `Property` where does that leave {{has(String)}}:

```text
gremlin> g.V(1).properties().has('name')
gremlin> g.V(1).properties().hasKey('name')
==>vp[name->marko]
```

Should it be deprecated in favor of `hasKey()` or Is there a reason to keep that signature?

@javeme your PR was focused on edges and i'm not sure what's involved in making sure this change makes these steps wholly consistent, but to make this feature "complete" I think that it needs to go an extra step to ensure that metaproperties also work:

```text
gremlin> g.V().properties().hasKey('location').properties().hasKey('startTime')
org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerProperty cannot be cast to org.apache.tinkerpop.gremlin.structure.Element
Type ':help' or ':h' for help.
Display stack trace? [yN]n
```

Also, I'm sorry, but I don't completely follow the issue you described with:

```text
ElementHelper.areEqual(final Property a, final Object b)
```

Could you please clarify what's wrong? If there are issues with olap we will need to sort those out before this can be merged. Thanks.

**Comment by javeme** [comment]
@spmallette Thanks.
> close yours as a "duplicate" and re-reference this PR to that issue

Done.

> if this capability can be safely targetted at the tp34 branch without breaking changes I think that would be a nice feature to have along our current 3.4.x release line

Yes, it is compatible with 3.4.x.  Let's push to tp34 branch.

>  it needs to go an extra step to ensure that metaproperties also work

Sure I also think it is needed to make these steps wholly consistent. I've tested the metaproperties case, and it's OK with this patch:
```java
gremlin> graph = TinkerFactory.createTheCrew()
==>tinkergraph[vertices:6 edges:14]
gremlin> g = graph.traversal()
==>graphtraversalsource[tinkergraph[vertices:6 edges:14], standard]
gremlin> g.V().properties().hasKey('location').properties().hasKey('startTime')
==>p[startTime->1997]
==>p[startTime->2001]
==>p[startTime->2004]
==>p[startTime->2005]
==>p[startTime->1990]
==>p[startTime->2000]
==>p[startTime->2006]
==>p[startTime->2004]
==>p[startTime->2007]
==>p[startTime->2011]
==>p[startTime->2014]
==>p[startTime->1982]
==>p[startTime->2005]
==>p[startTime->2009]
```

> Could you please clarify what's wrong

The Travis issue is caused by HadoopProperty dedup does not work, the root cause is Property comparison will compare the parent elements(here it's edges), but the same edges with two directions are not equal for StarOutEdge and StarInEdge. For TinkerEdge, the same edges with two directions are equal.
Is it necessary to unify the behavior of edges comparison? like StarEdge and TinkerEdge. I would also be pleasure to submit a patch if necessary.

**Comment by spmallette** [comment]
looks like you've created a new PR at #1224 against `tp34`. closing this one and we can continue conversation over there. @dkuppitz we'll look for your comment over there.

**Pull request closed without merging**
