### PR TITLE
TINKERPOP-2118 Bump to groovy 2.4.16

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-2118

All tests pass with `docker/build.sh -t -i`

VOTE +1

### CODE REVIEW

**Comment by robertdale** [comment]
VOTE +1

**Comment by FlorianHockmann** [comment]
VOTE +1

**Comment by FlorianHockmann** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE +1

**Pull request merged**
