### PR TITLE
TINKERPOP-2185 bump commons-configuration to 1.10.0.redhat-1

### PR DESCRIPTION
**Pull request by robertdale**
https://issues.apache.org/jira/browse/TINKERPOP-2185

### CODE REVIEW

**Comment by spmallette** [comment]
Travis doesn't appear to be able to deal:

```text
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache TinkerPop :: Gremlin Core 3.3.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for commons-configuration:commons-configuration:jar:1.10.0.redhat-1 is missing, no dependency information available
```

**Comment by robertdale** [comment]
We would have to add the RH repo to the pom - https://mvnrepository.com/repos/redhat-ga
Haven't gotten around to that yet.  I'm assuming it's public at this point.  But is that something we want to do anyway?

**Comment by spmallette** [comment]
not sure - this is going to gremlin-core so having a non-standard repo might mess with things like grape/plugins maybe. i wasn't 100% sure we'd use the RedHat thing...i figured it would take a bit of thought/discussion. 

of course, without something like the RedHat artifact, the version stays stuck with the security problem along 3.3.x and 3.4.x unless we choose to accept a major breaking change in either of those lines. i still don't know when we want to allow for such things (i.e. take a major breaking change to fix a security problem). i guess it's done on a case-by-case basis perhaps - so, is the seriousness of this commons-configuration issue enough to force us to bump 3.3.x and 3.4.x or can it wait for 3.5.x?

**Comment by robertdale** [comment]
Closing this for lack of supporting evidence as a security fix. TINKERPOP-2185 will be fixed via major version bump.

**Pull request closed without merging**
