### PR TITLE
provide examples where merge operator actually has an impact

### PR DESCRIPTION
**Pull request by mpollmeier**
see https://groups.google.com/d/msgid/gremlin-users/CD3873E8-F202-4717-92E4-700D6CA80603%40gmail.com

I wasn't able to test the generated documentation locally because I don't have hadoop running.

### CODE REVIEW

**Comment by spmallette** [comment]
do you happen to use docker? it's pretty easy to generate docs in that case: 

```text
docker/build.sh -d
```

**Comment by mpollmeier** [comment]
Interesting, yes I just did that and it did generate more docs, but not the reference documentation. I can't find it at least - where is it supposed to end up?

The end of the console output suggests that after a successful build it tries to do something with openbsd and hadoop and it fails. Is that what triggers the doc generation?

```
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [3:40.690s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [28.007s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [22.767s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [16.600s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [2.069s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [38.851s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [41.450s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [9.500s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [19.902s]
[INFO] Apache TinkerPop :: Gremlin Python ................ SUCCESS [8:42.556s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [2:18.967s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [2:35.916s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [1:21.021s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [28.799s]
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SUCCESS [0.115s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SUCCESS [18.551s]
[INFO] Apache TinkerPop :: Archetype - Server ............ SUCCESS [0.162s]
[INFO] Apache TinkerPop :: Gremlin Tools ................. SUCCESS [0.190s]
[INFO] Apache TinkerPop :: Gremlin Benchmark ............. SUCCESS [34.424s]
[INFO] Apache TinkerPop :: Gremlin Coverage .............. SUCCESS [0.394s]
[INFO] Apache TinkerPop :: Gremlin IO Test ............... SUCCESS [0.923s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:03.212s
[INFO] Finished at: Tue Mar 28 23:16:31 UTC 2017
[INFO] Final Memory: 180M/1098M
[INFO] ------------------------------------------------------------------------
 * Starting OpenBSD Secure Shell server sshd                                                                        [ OK ]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/security/authorize/RefreshAuthorizationPolicyProtocol
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.security.authorize.RefreshAuthorizationPolicyProtocol
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 19 more
Error: Could not find or load main class org.apache.hadoop.hdfs.tools.GetConf
Starting namenodes on []
localhost: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
localhost: starting namenode, logging to /usr/local/lib/hadoop-2.7.2/logs/hadoop-root-namenode-ca1a5ade0416.out
localhost: Error: A JNI error has occurred, please check your installation and try again
localhost: Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/security/authorize/RefreshAuthorizationPolicyProtocol
localhost:      at java.lang.ClassLoader.defineClass1(Native Method)
localhost:      at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
localhost:      at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
localhost:      at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
localhost:      at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
localhost:      at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
localhost:      at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
localhost:      at java.security.AccessController.doPrivileged(Native Method)
localhost: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
localhost: starting datanode, logging to /usr/local/lib/hadoop-2.7.2/logs/hadoop-root-datanode-ca1a5ade0416.out
localhost: Error: Could not find or load main class org.apache.hadoop.hdfs.server.datanode.DataNode
Error: Could not find or load main class org.apache.hadoop.hdfs.tools.GetConf
Error: Could not find or load main class org.apache.hadoop.fs.FsShell
Error: Could not find or load main class org.apache.hadoop.fs.FsShell
starting yarn daemons
starting resourcemanager, logging to /logs/yarn-root-resourcemanager-ca1a5ade0416.out
nice: /bin/yarn: No such file or directory
localhost: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
localhost: starting nodemanager, logging to /logs/yarn-root-nodemanager-ca1a5ade0416.out
localhost: nice: /bin/yarn: No such file or directory
Hadoop is not running, be sure to start it before processing the docs.
Untagged: tinkerpop:build-1490739696
Deleted: sha256:d6d41f1c188606fc3495f5728732541f0b07b228831809ad5db2795b1939c0e5
Deleted: sha256:8cd45aaa133f9d50b8ace175b84981c1fbd7da9a237cb77ec0d60406b6e2636f
Deleted: sha256:31e5a4ebfb1e28e3fc3129e96e5f406cc5fbe9195118a9f6b420097b98e35fba
Deleted: sha256:46ad873cde8de4d8e7ca33499cc069275da9946df6f649737ea9d49d41b89ccc
Deleted: sha256:19b5206fee81e30a3e40b5eb387030e17ad9cb8423b37089312f083eddc8d700
Deleted: sha256:09ac73ee794194ec6c05ead655b7ca46fe61fd607ffb63075d995f512b5a3f69
```

**Comment by mpollmeier** [comment]
```
docker --version
Docker version 17.03.0-ce, build 60ccb2265b
```

**Comment by spmallette** [comment]
weird versioning scheme docker switched to. @dkuppitz any ideas what that failure means?

**Comment by dkuppitz** [comment]
Hmm, never seen it before, but since it's security related, Docker probably didn't get enough permissions..? Does the user, that is used to run the Docker daemon, have root privileges?

**Comment by robertdale** [comment]
@mpollmeier Have you used tinkerpop docker before? I'm wondering if you have an old image. If so, maybe try rebuilding your images.  I was able to run this successfully with the same docker version on Fedora 24.

**Comment by robertdale** [comment]
@spmallette @dkuppitz Separate issue:  when I pull up the initial URL to look at the docs, it's local -
 `http://172.17.0.2/` .

Anchor links to the same page are also local - `http://172.17.0.2/#tutorials` .

However, all links to other pages are remote!  Also, you can't just replace the server name with the local IP, the URL is slightly different.  e.g.
`http://tinkerpop.apache.org/docs/3.3.0-SNAPSHOT/reference`
must be changed to  `http://172.17.0.2/reference/` in order to view it locally.

Let me know if this is your experience and if you want me to create a ticket for it.

**Comment by dkuppitz** [comment]
I know, that's annoying and I think we mainly did it like this, because the local directory structure is different from the one that we publish. Might be a good idea to have a ticket for that as I don't think it's too hard to get the directories right locally.

Back to this PR: `docker/build.sh -d` seems to work fine for me for this PR. Not yet done (processing gremlin-applications atm), but no errors or whatsoever during the Hadoop initialization phase.

**Comment by dkuppitz** [comment]
`implementations-giraph` currently fails for me, but that happens frequently on my system (and has nothing to do with this PR). `the-traversal` looks good.

VOTE: +1

**Comment by mpollmeier** [comment]
@robertdale I haven't run the tinkerpop docker before, so it did a fresh download of all the docker images

@dkuppitz the docker daemon runs as root, if I read the output here correctly:
```
ps -ef|grep docker
root       580     1  0 12:16 ?        00:00:00 /usr/bin/dockerd -H fd://
root       642   580  0 12:16 ?        00:00:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
```

Anyway, these issues shouldn't stop the PR from getting merged.

**Comment by spmallette** [comment]
no - shouldn't stop the pr. it would be nice to identify the problem though. always interesting that docker is supposed to be the great environment equalizer and then you have this kinda of nonsense.

**Comment by robertdale** [comment]
I like how the previous example shows the vertices before applying sack(). I think it would be useful to see that before 1 and before 3.

Why was the example withBulk(false) removed?  I don't understand enough about it to know if it was useful.

Otherwise, the format and display is correct.

**Comment by mpollmeier** [comment]
@spmallette I'm also surprised, but not a docker expert. I'm happy to try out other stuff to get to the bottom of that problem, just let me know if you have some idea. 

@robertdale Re the examples without sack: I don't mind, they just didn't look very interesting to me. I just added them back in, same goes for withBulk

**Comment by spmallette** [comment]
@mpollmeier i just noticed that this changes is targetted to `master`. seems like it would be better suited for the `tp32` branch. any reason not to target that branch instead?

**Comment by robertdale** [comment]
Updates look good

**Comment by robertdale** [comment]
I rebuilt my images and did not encounter any errors.  Maybe something didn't get pulled down like it should.  I've seen connection resets when pulling down the python stuff.

**Comment by mpollmeier** [comment]
@spmallette I simply assumed master should be the target, just changed it to tp32 (after rebasing the commit onto that branch and force pushing to my repo).

**Comment by robertdale** [comment]
@mpollmeier it lost the additions

**Comment by mpollmeier** [comment]
@robertdale thanks for checking. Must have happened during rebase. Here they are again.

**Comment by robertdale** [comment]
VOTE +1

**Comment by spmallette** [comment]
docs generate for me - VOTE +1

@mpollmeier in the future please remember that you are free to +1 your own PR as a committer vote. Anyway, you are free to merge this in now.  Before you push please remember to merge tp32 to master locally. at that point you can push master and then tp32. please let me know if you have any questions.

**Comment by mpollmeier** [comment]
@spmallette I don't have write access to this repository, can you either grant them to me or merge for me?

**Comment by spmallette** [comment]
hmmm - cant' believe that wasn't taken care of. what's your apache id?

**Comment by mpollmeier** [comment]
I've just contacted you on hipchat, that might be a better place for figuring out those access rights.

**Comment by mpollmeier** [comment]
this was merged to tp32 and master and should have been closed automatically here, for some reason the sync-script didn't capture that. closing manually.

**Pull request closed without merging**
