### PR TITLE
TINKERPOP-1879 Fixed gremlin.sh handling of = in flags

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1879

Builds with `mvn clean install -pl gremlin-console -DskipIntegrationTests=false`

VOTE +1

### CODE REVIEW

**Comment by robertdale** [comment]
Those tests pass?  It doesn't seem to work for me on the cli.

**Comment by spmallette** [comment]
What were you trying? seems to work for me:

```text
$ cat x.groovy
println "123"
$ bin/gremlin.sh -e x.groovy
123
$ bin/gremlin.sh -e=x.groovy
123
$ bin/gremlin.sh -i=x.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
123
gremlin> :x
$ bin/gremlin.sh --interactive=x.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
123
gremlin> :x
$ bin/gremlin.sh --execute=x.groovy
123
$ bin/gremlin.sh --execute x.groovy
123
```

**Comment by robertdale** [comment]
Yeah, ok, apparently I never actually switched branches.  Time to get some coffee....
VOTE +1

**Comment by dkuppitz** [comment]
Hmm, although it's functional, it looks kinda weird. The common patterns are:

* `-s` and `-s arg` for short options
* `--long`, `--long arg` and `--long="arg"` for long options

I've never seen short options allowing the equals sign.

**Comment by spmallette** [comment]
true - it just sorta worked that way i guess. i didn't go out of my way to disallow it.  should i change it?

**Comment by dkuppitz** [comment]
Yea, I think that would be better. Looks like an easy change, you'd just feed `normalizeArgs` with the long options only.

**Comment by spmallette** [comment]
If i filter out the short options and someone does `-e=x.groovy` (or `-i=`) then it hangs the load of the console (which was the original problem i wanted to solve). I guess to properly handle this, i'd need to invalidate the short options when they contain an "=" and just print an error message. should i do that?

**Comment by spmallette** [comment]
ok - i think i have it right now:

```text
$ cat x.groovy
println "test"
$ bin/gremlin.sh -e x.groovy
test
$ bin/gremlin.sh -e=x.groovy
Gremlin file not found at [=x.groovy].
$ bin/gremlin.sh -i=x.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
Gremlin file not found at [=x.groovy].
gremlin> :x
$ bin/gremlin.sh -i x.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
test
gremlin> :x
```

Existing console integration tests all pass. Good?

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
