### PR TITLE
TINKERPOP-1729: Remove deprecated select steps.

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1729

There is no point is crying over spilled milk. The deed is done. It had to be done.

VOTE +1.

### CODE REVIEW

**Comment by spmallette** [comment]
I had some trouble with this, but once I rebased on master it was fine. I think it's just based on a bad commit on master so once it merges it should be fine.

All tests pass with `docker/build.sh -t -i`

VOTE +1

**Comment by okram** [comment]
Yes -- tested again to be safe.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:22 h
[INFO] Finished at: 2017-07-18T16:38:37-06:00
[INFO] Final Memory: 162M/1473M
[INFO] ------------------------------------------------------------------------
```

**Comment by okram** [comment]
@dkuppitz Can you review this please?

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by okram** [comment]
Some reason the asfbot was unable to pick up this merge. This was merged -- closing.

**Pull request closed without merging**
