### PR TITLE
Minor tutorial fix

### PR DESCRIPTION
**Pull request by volkovs**
Gremlin Server is started without REST channel (so next attempt to POST Gremlin query fails).

### CODE REVIEW

**Comment by spmallette** [comment]
can you please-retarget your pull request to the tp31 branch - it should be fixed all the way back to 3.1.x - thanks!

**Comment by volkovs** [comment]
all right #653

**Comment by volkovs** [comment]
All right, no problem, #654.
Do you need a separate pull request for branch tp32 ?

**Comment by spmallette** [comment]
no - i can handle the appropriate merges in this case.

**Comment by spmallette** [comment]
merged to all branches. can you please close this? thanks.

**Pull request closed without merging**
