### PR TITLE
TINKERPOP-1824 Bump netty to 4.0.52

### PR DESCRIPTION
**Pull request by robertdale**
https://issues.apache.org/jira/browse/TINKERPOP-1824

Latest bug-fix release.

VOTE +1

### CODE REVIEW

**Comment by spmallette** [comment]
Does this build fully with integration tests any everything? i imagine there are also no new dependencies to consider or significant changes to their NOTICE? actually, the second half of that last question made me go look at our NOTICE which is a bit out of date - can you please update this for netty (i'll look at the rest):

https://github.com/apache/tinkerpop/blob/master/gremlin-console/src/main/static/NOTICE#L57
https://github.com/apache/tinkerpop/blob/master/gremlin-server/src/main/static/NOTICE#L58

**Comment by robertdale** [comment]
```
$ sh docker/build.sh -i -t -n
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:32:29.815s
[INFO] Finished at: Thu Nov 02 17:00:29 UTC 2017
[INFO] Final Memory: 180M/2359M
[INFO] ------------------------------------------------------------------------
```

**Comment by robertdale** [comment]
@spmallette Updated NOTICE with latest version.  No new deps.

**Comment by spmallette** [comment]
Sorry I might have conflicted your PR with my NOTICE fixes i just pushed - a quick rebase should fix that...otherwise:

VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
