### PR TITLE
 	Added getProjectKeys in ProjectStep

### PR DESCRIPTION
**Pull request by seanbarzilay**
One of my strategies requires getting the project keys

### CODE REVIEW

**Comment by okram** [comment]
I'm happy to merge this. Question -- why do you need this information? (out of curiosity).

VOTE +1.

**Comment by seanbarzilay** [comment]
I have my own implementation for ProjectStep in [Unipop](https://github.com/unipop-graph/unipop) that optimizes the number of queries I make

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
@seanbarzilay do you mind cleaning up the commit history a bit? It would be nice to have one commit that we can merge for this small change.

**Comment by seanbarzilay** [comment]
@spmallette done

**Comment by spmallette** [comment]
pretty: VOTE +1 - give the last comment @okram laid out there it sounds like he will handle the merge now that you have 3X +1.

**Comment by okram** [comment]
merged. in the future, please update CHANGELOG or provide a note about what to add to the CHANGELOG on merge. Also, I just addded you change because it was targeted to master and it can go in `tp32`. Also, should I want to make this an `UnmodifiableList` that is returned. Is that okay? thanks for the PR.

**Comment by okram** [comment]
(please manually close this PR)

**Comment by seanbarzilay** [comment]
@okram  wonderful

**Pull request closed without merging**
