### PR TITLE
TINKERPOP-1488: Make LazyBarrierStrategy part of the default TraversalStrategies

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1488

`LazyBarrierStrategy` is now a default `OptimizationStrategy`. Rewrote `LazyBarrierStrategy` and with @dkuppitz's help, we were able to make all tested traversals either equal or faster than without `LazyBarrierStrategy`. This is a really cool optimization.

```
gremlin> graph = TinkerGraph.open()
==>tinkergraph[vertices:0 edges:0]
gremlin> graph.io(gryo()).readGraph('data/grateful-dead.kryo')
==>null
gremlin>
gremlin> g1 = graph.traversal().withoutStrategies(LazyBarrierStrategy.class)
==>graphtraversalsource[tinkergraph[vertices:808 edges:8049], standard]
gremlin> g2 = graph.traversal()
==>graphtraversalsource[tinkergraph[vertices:808 edges:8049], standard]
gremlin>
gremlin> clock(10){g1.V().out().in().out().count().iterate()}
==>1073.5150449999999
gremlin> clock(10){g2.V().out().in().out().count().iterate()}
==>8.8109061
gremlin>
gremlin> clock(100){g1.V().out().out().count().iterate()}
==>18.75418462
gremlin> clock(100){g2.V().out().out().count().iterate()}
==>2.04183101
gremlin>
gremlin> clock(100){g1.V().out().values('performances').count().iterate()}
==>1.67867484
gremlin> clock(100){g2.V().out().values('performances').count().iterate()}
==>1.4292696999999999
gremlin>
gremlin> clock(100){g1.V().out().values('performances').is(gt(10)).iterate()}
==>1.76701077
gremlin> clock(100){g2.V().out().values('performances').is(gt(10)).iterate()}
==>1.47417542
gremlin>
gremlin> clock(100){g1.V().has('name','Garcia').out().out().iterate()}
==>0.23742839999999998
gremlin> clock(100){g2.V().has('name','Garcia').out().out().iterate()}
==>0.24021971999999997
gremlin>
gremlin> clock(100){g1.V().as('a').out('sungBy').in('sungBy').where(neq('a')).iterate()}
==>26.31896202
gremlin> clock(100){g2.V().as('a').out('sungBy').in('sungBy').where(neq('a')).iterate()}
==>21.811683509999998
gremlin>
gremlin> clock(100){g1.V().has('name','DARK STAR').out('followedBy').aggregate('a').out('followedBy').in('followedBy').where(not(within('a'))).groupCount().by('name').iterate()}
==>24.6694559
gremlin> clock(100){g2.V().has('name','DARK STAR').out('followedBy').aggregate('a').out('followedBy').in('followedBy').where(not(within('a'))).groupCount().by('name').iterate()}
==>1.9376707899999999
```
If this is VOTE'd in then, I will merge it after TINKERPOP-1455 is merged so we can do parameterization via `Configuration`.

VOTE +1.

### CODE REVIEW

**Comment by spmallette** [comment]
This is a breaking change in the sense as the package name changed. I doubt it should break most users, but a breaking change nonetheless. I think it would have been better to deprecate it where it was and copy/paste to the new package There would be two classes that did the same thing, but it would all happen without a break. Then we just delete the deprecated one for 3.3.0.

**Comment by twilmes** [comment]
The code and tests look good to me.  `mvn clean install` also ran without issue.

VOTE: +1

**Comment by okram** [comment]
@spmallette -- good call. I added back `finalization.LazyBarrierStrategy` and @Deprecated it.

**Comment by spmallette** [comment]
All tests pass with `docker/build.sh -t -i`

VOTE +1

**Pull request merged**
