### PR TITLE
Implement list filtering `none()` step

### PR DESCRIPTION
**Pull request by ryn5**
List filtering step that takes a predicate and filters out lists that fail to have none of their elements satisfying the predicate.  Implementation is based on https://github.com/apache/tinkerpop/pull/2228.  These changes should come after https://github.com/apache/tinkerpop/pull/2408 and https://github.com/apache/tinkerpop/pull/2377 are merged.

### CODE REVIEW

**Comment by Cole-Greer** [comment]
Thanks for putting this all together Ryan, the changes look good to me right now, although the diff is quite complex given the inclusion of all of the renaming none() to discard() stuff. I can give a tentative approval for now, although I would like to take another look at this after #2408 and #2377 have been merged (which should greatly simplify the diff in this PR).

**Comment by Cole-Greer** [comment]
Thanks Ryan. I've gone through the docs, the feature tests, NoneStep, and NoneStepTest and it all looks good to me.

VOTE +1

**Review by xiazcy — APPROVED** [review]
LGTM. Just a minor nit for the docs, but not required. 

VOTE +1

**Comment by vkagamlyk** [comment]
VOTE+1

**Pull request merged**
