### PR TITLE
Added correct setting of future exceptions, pursuant to TINKERPOP-1883

### PR DESCRIPTION
**Pull request by dancollins34**
https://issues.apache.org/jira/browse/TINKERPOP-1883

### CODE REVIEW

**Comment by davebshow** [comment]
LGTM 

VOTE +1

**Comment by spmallette** [comment]
@dancollins34 sorry it took me a while to take a look at this - thanks for submitting it. is this also a problem on 3.2.x? if so, this pull request should be re-targeted at the tp32 branch.

**Comment by spmallette** [comment]
@davebshow this should target tp32 is that correct?

**Comment by davebshow** [comment]
Yes this affects both 32 and master

**Comment by spmallette** [comment]
i think we can just CTR this in - it's pretty simple. i'll just cherry pick to tp32 and merge from there, then manually close this

**Comment by davebshow** [comment]
sweet

**Pull request closed without merging**
