### PR TITLE
TINKERPOP-1338 Bumped groovy to 2.4.7

### PR DESCRIPTION
**Pull request by robertdale**
No new dependencies introduced.
No other dependency versions changed.

Successful build and verify with:
mvn clean install -pl gremlin-shaded,gremlin-core,gremlin-test,gremlin-groovy,gremlin-groovy-test,tinkergraph-gremlin,neo4j-gremlin,gremlin-driver,gremlin-console,gremlin-server,gremlin-archetype && mvn verify -pl gremlin-server -DskipIntegrationTests=false -DincludeNeo4j

(excludes giraph-gremlin, hadoop-gremlin,spark-gremlin because I have separate issues building them)

### CODE REVIEW

**Comment by robertdale** [comment]
Fixed my Spark issue. Wanted to rebuild since giraph, hadoop, and spark have some dependency on groovy.

Builds cleanly with mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false

**Comment by spmallette** [comment]
Note that it's not sufficient in this case to only run gremlin server integration tests. You should probably run the whole suite. When i run that with docker via `docker/build.sh -t -i -n` i get tons of:

```text
Caused by: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: void
	at com.esotericsoftware.kryo.Kryo.newSerializer(Kryo.java:335)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:314)
	at com.twitter.chill.KryoBase.newDefaultSerializer(KryoBase.scala:48)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:307)
	at com.esotericsoftware.kryo.Kryo.register(Kryo.java:351)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.GryoRegistrator.registerClasses(GryoRegistrator.java:94)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.GryoRegistrator.registerClasses(GryoRegistrator.java:65)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:124)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:124)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:124)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.IoRegistryAwareKryoSerializer.newKryo(IoRegistryAwareKryoSerializer.java:57)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.kryoshim.unshaded.UnshadedKryoShimService.initialize(UnshadedKryoShimService.java:144)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.kryoshim.unshaded.UnshadedKryoShimService.applyConfiguration(UnshadedKryoShimService.java:106)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.KryoShimServiceLoader.load(KryoShimServiceLoader.java:125)
	at org.apache.tinkerpop.gremlin.spark.process.computer.SparkHadoopGraphGryoRegistratorProvider.getBaseConfiguration(SparkHadoopGraphGryoRegistratorProvider.java:48)
	at org.apache.tinkerpop.gremlin.AbstractGraphProvider.newGraphConfiguration(AbstractGraphProvider.java:70)
	at org.apache.tinkerpop.gremlin.GraphProvider.standardGraphConfiguration(GraphProvider.java:144)
	at org.apache.tinkerpop.gremlin.GraphManager$ManagedGraphProvider.standardGraphConfiguration(GraphManager.java:132)
	at org.apache.tinkerpop.gremlin.AbstractGremlinTest.setup(AbstractGremlinTest.java:81)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:54)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:212)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.esotericsoftware.kryo.Kryo.newSerializer(Kryo.java:322)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:314)
	at com.twitter.chill.KryoBase.newDefaultSerializer(KryoBase.scala:48)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:307)
	at com.esotericsoftware.kryo.Kryo.register(Kryo.java:351)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.GryoRegistrator.registerClasses(GryoRegistrator.java:94)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.GryoRegistrator.registerClasses(GryoRegistrator.java:65)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:124)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:124)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:124)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.IoRegistryAwareKryoSerializer.newKryo(IoRegistryAwareKryoSerializer.java:57)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.kryoshim.unshaded.UnshadedKryoShimService.initialize(UnshadedKryoShimService.java:144)
	at org.apache.tinkerpop.gremlin.spark.structure.io.gryo.kryoshim.unshaded.UnshadedKryoShimService.applyConfiguration(UnshadedKryoShimService.java:106)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.KryoShimServiceLoader.load(KryoShimServiceLoader.java:125)
	at org.apache.tinkerpop.gremlin.spark.process.computer.SparkHadoopGraphGryoRegistratorProvider.getBaseConfiguration(SparkHadoopGraphGryoRegistratorProvider.java:48)
	at org.apache.tinkerpop.gremlin.AbstractGraphProvider.newGraphConfiguration(AbstractGraphProvider.java:70)
	at org.apache.tinkerpop.gremlin.GraphProvider.standardGraphConfiguration(GraphProvider.java:144)
	at org.apache.tinkerpop.gremlin.GraphManager$ManagedGraphProvider.standardGraphConfiguration(GraphManager.java:132)
	at org.apache.tinkerpop.gremlin.AbstractGremlinTest.setup(AbstractGremlinTest.java:81)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:54)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:212)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.NullPointerException: null
```

I assume this is because of #353 (just a guess) - perhaps you need to rebase now that this issue is merged?

**Comment by spmallette** [comment]
looks like this is failing in master too..........so it's unrelated to your change. we will need to get that fixed and at that point you should rebase and try to full integration tests suite. i'll post back here when that's fixed on master

**Comment by robertdale** [comment]
This PR does include #353 but not #354 . In the meantime, I'm setting up docker. Thanks.

**Comment by robertdale** [comment]
I rebased to include @okram 's fix in the jira ticket.  4.5 hours later, "docker/build.sh -t -i -n" passed!

**Comment by okram** [comment]
VOTE +1.

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Pull request merged**
