### PR TITLE
TINKERPOP-1474 GraphSON decode of Vertex and Edge properties

### PR DESCRIPTION
**Pull request by bjmoor**
If the server sends properties back with the Vertices and Edges, gremlin_python should deserialize the properties and make them available.

This patch will add the properties to the returned Vertex, Edge, VertexProperty or Property, if and only if, the "properties" are returned.

By default, gremlin-server will not return Properties or Labels of elements.  However, when using a DetachedFactory HaltedTraverserStrategy, the server will return these properties.

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for this. Would you mind including tests for `Edge` and `VertexProperty`? Also, could you please edit your PR to have TINKERPOP-1474 as the prefix to the rest of your text in the name as in:

"TINKERPOP-1474 GraphSON decode of Vertex and Edge properties"

This change applies to that ticket I think.

**Comment by okram** [comment]
Dah. I didn't see this ticket. I'm doing this (along with other things) in TINKERPOP-1520. Hmm... perhaps you can provide a PR to that branch ... In particular your test cases.

**Comment by spmallette** [comment]
TINKERPOP-1420 has merged to master. @bjmoor do you want to rebase your PR? note this area of development is still somewhat in flux on master given:

https://issues.apache.org/jira/browse/TINKERPOP-1565

Perhaps the best option would be to target this work at the tp32 branch where GraphSON 2.0 is stable. wdyt?

**Comment by spmallette** [comment]
@okram pinged me on the side and filled me in with some background info i wasn't aware of - the short of it is that a lot of work has been done in this area on the aforementioned tickets and if you'd like to contribute you should probably coordinate with those working on TINKERPOP-1565 at this point.

**Comment by bjmoor** [comment]
It looks like the work being done in TINKERPOP-1565 will be addressing the issue which this PR was attempting to address, and probably in a more effective manner.  Should I just close this PR?

**Comment by spmallette** [comment]
yes - i think you can close this one since the work is already underway elsewhere. thanks for submitting this though.

**Pull request closed without merging**
