### PR TITLE
TINKERPOP-2071: gremlin-python: g:Set graphson deserializer should return a python set

### PR DESCRIPTION
**Pull request by aboudreault**
If there is additional documentation you would like somewhere... please, point me where.

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for submitting this....Travis seems unhappy on the gremlin-python version of the build....could you please have a look at that? Also, this looks like it needs a rebase now that we have the tp33 branch re-opened for development. That should get CHANGELOG setup for new entries. Please don't include the JIRA issue there - just a bullet point with your representation of what changed will suffice.

**Comment by spmallette** [comment]
I think there needs to be a documentation update too - i just noticed this:

http://tinkerpop.apache.org/docs/3.3.4/reference/#_limitations

**Comment by aboudreault** [comment]
@spmallette I addressed comments and fixed the initial issue we were seeing in travis. However, I am not able to reproduce this one: https://travis-ci.org/apache/tinkerpop/jobs/445261231#L7397 , everything seems to pass locally. Any pointer?

**Comment by spmallette** [comment]
I re-ran the travis build and the error is gone. probably a fluke of travis or something. I guess this is good now.  do you happen to know if there is a test for the alternative scenario somewhere (i.e. where a set becomes a list)?

**Comment by aboudreault** [comment]
@spmallette Let me look at how this scenario stuff works. I will add one that return a list.

**Comment by spmallette** [comment]
I think this one is ok at this point - note the creation of https://issues.apache.org/jira/browse/TINKERPOP-2082 for other GLVs 

VOTE +1

**Pull request merged**
