### PR TITLE
[TINKERPOP-2927] Relax steps extensibility strictness

### PR DESCRIPTION
**Pull request by porunov**
In this commit the next changes are done for the Step classes:
- Make private fields as protected
- Allow to overwride any method by removing `final` keyword
- Allow to extend any Step class by removing `final` keyword
- Add getter methods for some fields which might be useful for Step information retrieval

Issue: https://issues.apache.org/jira/browse/TINKERPOP-2927
Discussion: https://lists.apache.org/thread/vjbjh29kwjhd5lcmkqqqqrhw7rw2ynh9

### CODE REVIEW

**Comment by Cole-Greer** [comment]
Thanks @porunov for submitting this PR. The changes all look valid to me, but opening all of this up is a big change to TinkerPop and needs further consideration. Could you make a [DISCUSS] thread on the dev maillist to ensure that the community is aligned behind this change?

**Comment by porunov** [comment]
> Thanks @porunov for submitting this PR. The changes all look valid to me, but opening all of this up is a big change to TinkerPop and needs further consideration. Could you make a [DISCUSS] thread on the dev maillist to ensure that the community is aligned behind this change?

Thank you for the feedback. I opened the discussion thread here: https://lists.apache.org/thread/vjbjh29kwjhd5lcmkqqqqrhw7rw2ynh9

**Comment by porunov** [comment]
Marked this PR as draft for now until we have some consensus in the [discussion thread](https://lists.apache.org/thread/vjbjh29kwjhd5lcmkqqqqrhw7rw2ynh9).
I believe the following PRs should be merged instead as for now:
https://github.com/apache/tinkerpop/pull/2029
https://github.com/apache/tinkerpop/pull/2030
https://github.com/apache/tinkerpop/pull/2031

**Comment by Cole-Greer** [comment]
Going to close this PR based on the discussion on the dev list.
https://lists.apache.org/thread/vjbjh29kwjhd5lcmkqqqqrhw7rw2ynh9

Additional steps can be opened up in the future but will be handled on a case by case basis. See dev list discussion for more details.

**Pull request closed without merging**
