### PR TITLE
Gremlin-Go: Added support for additional types

### PR DESCRIPTION
**Pull request by vkagamlyk**
Gremlin-Go: Added serialization for classType, bigDecimalType, byteBuffer, metricsType, traversalMetricsType

### CODE REVIEW

**Comment by lyndonbauto** [comment]
VOTE+1 thanks!

**Review by mikepersonick — APPROVED** [review]
VOTE +1 (someone will squash these commits before merging?)

**Comment by lyndonbauto** [comment]
@mikepersonick 
> VOTE +1 (someone will squash these commits before merging?)

Yep

**Comment by krlawrence** [comment]
VOTE +1 Thanks for all the work on this

**Comment by lyndonbauto** [comment]
That's 3 VOTE+1's, I am going to merge. Thanks @vkagamlyk!

**Pull request merged**
