### PR TITLE
TINKERPOP-2749: Spark Gremlin Windows Build Error Fixes

### PR DESCRIPTION
**Pull request by L0Lmaker**
Spark Build on Windows Causes Errors along the lines of:
```
[ERROR] Failures: 
[ERROR] org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck.shouldSupportGraphSONIoRegistry(org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck)      
[INFO]   Run 1: PASS
[ERROR]   Run 2: SparkIoRegistryCheck.shouldSupportGraphSONIoRegistry:67->AbstractIoRegistryCheck.checkGraphSONIoRegistryCompliance:98
[INFO]
[ERROR] org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck.shouldSupportGryoV1d0IoRegistry(org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck)      
[INFO]   Run 1: PASS
[ERROR]   Run 2: SparkIoRegistryCheck.shouldSupportGryoV1d0IoRegistry:57->AbstractIoRegistryCheck.checkGryoV1d0IoRegistryCompliance:75
[INFO]
[ERROR] org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck.shouldSupportGryoV3d0IoRegistry(org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck)      
[INFO]   Run 1: PASS
[ERROR]   Run 2: SparkIoRegistryCheck.shouldSupportGryoV3d0IoRegistry:62->AbstractIoRegistryCheck.checkGryoV3d0IoRegistryCompliance:87
```
These failures are caused by the usage of the `File.delete()` function calls to delete temp files generated during runtime. This operation fails on Windows as the file is still actively open in the process and on Windows, active files cannot be deleted until a all processes stop using it.

`File.deleteOnExit()` deletes the file when the virtual machine terminates.

Link to Issue: [TINKERPOP-2749](https://issues.apache.org/jira/browse/TINKERPOP-2749)

### CODE REVIEW

**Review by FlorianHockmann — COMMENTED** [review]
The changes look good to me, but can't we now also add a Windows build for Spark to GH Actions?

**Comment by lyndonbauto** [comment]
VOTE+1 pending GH action for spark being enabled.

**Comment by L0Lmaker** [comment]
There are two maven commands that are currently run on the Spark Gremlin related jobs. `mvn clean install ...` and `mvn verify ...`. As of now the `mvn clean install ...` command builds successfully, whereas `mvn verify ...` does not. 

As the scope of the [issue](https://issues.apache.org/jira/browse/TINKERPOP-2749) is to make Tinkerpop build successfully on Windows, I suggest creating an issue regarding the `mvn verify ...` command and proceeding with just `mvn clean install ...` for now.

**Comment by FlorianHockmann** [comment]
> As the scope of the [issue](https://issues.apache.org/jira/browse/TINKERPOP-2749) is to make Tinkerpop build successfully on Windows, I suggest creating an issue regarding the mvn verify ... command and proceeding with just mvn clean install ... for now.

Sounds good to me. I just assumed that you wanted to include `mvn verify` here already as you did that for javascript, but just concentrating on getting `mvn clean` without tests running on Windows first makes sense to.

VOTE +1

**Comment by lyndonbauto** [comment]
Merging with lazy consensus.

**Pull request merged**
