### PR TITLE
TINKERPOP-2951: add translator to the Go GLV

### PR DESCRIPTION
**Pull request by itaywol**
Added to gremlingo the ability to translate bytecode to gremlin-groovy string.

This addresses the following [ticket](https://issues.apache.org/jira/browse/TINKERPOP-2951)

### CODE REVIEW

**Comment by Cole-Greer** [comment]
Thanks for putting this together. I will try to complete a full review today.

If possible, could you rebase your branch to [#3.5-dev](https://github.com/apache/tinkerpop/tree/3.5-dev) and target the PR to that branch as well? That will ensure that these changes will make it into all of the upcoming releases (3.5.7, 3.6.5, 3.7.0). If this is too much of a hassle don't worry about it, we can fix it up during the merge.

In case you aren't aware, we just kicked off code freeze week for our upcoming releases. In my opinion this change is small enough that we can sneak it in during code freeze as long as there are no significant concerns from review.

**Comment by vkagamlyk** [comment]
Hi Itay,
Thanks for your contribution!

This PR is missing support for some types like integers other then `int`, bool, dates, collections, predicates, strategies, etc.

For comprehensive list of test cases, please take a look [at translator tests for Python](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/tests/process/test_translator.py) or other GLV implementation.

Would also be nice to mention this PR changes in [changelog](https://github.com/apache/tinkerpop/blob/master/CHANGELOG.asciidoc)

**Comment by Cole-Greer** [comment]
Hi Itay,

I wanted to follow up on my previous comment and build off of what Valentyn's comment. As Valentyn mentioned this will require support for additional types and more testing. I also think it would be nice if the tests were to use a `GraphTraversal` to construct the `Bytecode` similar to what is done in the python translator tests, I believe this would make the tests easier to read and write. Let me know if you need any help with this.

There is a bit of a time crunch if you want to get this in our upcoming release as we are currently in code freeze. I think all of the python translator tests will need to be translated over and need to pass before we can proceed here. Also it would ideally be completed tomorrow to avoid jeopardizing the release. Please let me know if you have any questions regarding this. I will make a best effort to help get this included in the release but due to the timing it cannot be guaranteed.

**Comment by itaywol** [comment]
> Thanks for putting this together. I will try to complete a full review today.
> 
> If possible, could you rebase your branch to [#3.5-dev](https://github.com/apache/tinkerpop/tree/3.5-dev) and target the PR to that branch as well? That will ensure that these changes will make it into all of the upcoming releases (3.5.7, 3.6.5, 3.7.0). If this is too much of a hassle don't worry about it, we can fix it up during the merge.
> 
> In case you aren't aware, we just kicked off code freeze week for our upcoming releases. In my opinion this change is small enough that we can sneak it in during code freeze as long as there are no significant concerns from review.

Yeah sure i can move the commit.



> Hi Itay, Thanks for your contribution!
> 
> This PR is missing support for some types like integers other then `int`, bool, dates, collections, predicates, strategies, etc.
> 
> For comprehensive list of test cases, please take a look [at translator tests for Python](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/tests/process/test_translator.py) or other GLV implementation.
> 
> Would also be nice to mention this PR changes in [changelog](https://github.com/apache/tinkerpop/blob/master/CHANGELOG.asciidoc)

I will overview it and append more tests.

> Hi Itay,
> 
> I wanted to follow up on my previous comment and build off of what Valentyn's comment. As Valentyn mentioned this will require support for additional types and more testing. I also think it would be nice if the tests were to use a `GraphTraversal` to construct the `Bytecode` similar to what is done in the python translator tests, I believe this would make the tests easier to read and write. Let me know if you need any help with this.
> 
> There is a bit of a time crunch if you want to get this in our upcoming release as we are currently in code freeze. I think all of the python translator tests will need to be translated over and need to pass before we can proceed here. Also it would ideally be completed tomorrow to avoid jeopardizing the release. Please let me know if you have any questions regarding this. I will make a best effort to help get this included in the release but due to the timing it cannot be guaranteed.

I will try to get this as quickly as possible ( Today :) )

**Comment by itaywol** [comment]
Moving the work to a different PR
https://github.com/apache/tinkerpop/pull/2160
This can be closed for now

**Pull request closed without merging**
