### PR TITLE
TINKERPOP-2219 Upgrade Netty dependency to 4.1.32

### PR DESCRIPTION
**Pull request by divijvaidya**
https://issues.apache.org/jira/browse/TINKERPOP-2219

**Testing**

gremlin-driver: mvn clean install -DskipIntegrationTests=false
gremlin-server: mvn clean install -DskipIntegrationTests=false

### CODE REVIEW

**Comment by spmallette** [comment]
VOTE +1

**Comment by robertdale** [comment]
Need a `CHANGELOG` entry.

**Comment by spmallette** [comment]
I should have wrote that I would be fine to do that on merge. just a note about this generally...we usually do a CHANGELOG entry for netty version bumps as that is a major dependency.  

Another change that needs to be there is the update to the NOTICE files for the binaries:

https://github.com/apache/tinkerpop/blob/master/gremlin-console/src/main/static/NOTICE#L51
https://github.com/apache/tinkerpop/blob/master/gremlin-server/src/main/static/NOTICE#L52

technically, there should also be a check to see that the netty NOTICE hasn't changed in any way of substance that would trigger a change to our NOTICE. @divijvaidya you can read more about LICENSE/NOTICE stuff here in case you are interested (hint: it's not interesting, but it's what we need to do to be compliant with the ASF and its license):

http://tinkerpop.apache.org/docs/current/dev/developer/#dependencies

**Comment by divijvaidya** [comment]
My bad. I missed the part about dependencies in the [dev documentation](http://tinkerpop.apache.org/docs/current/dev/developer/#dependencies). I will make the changes once we resolve what version we want to upgrade to (discussion ongoing as part of the JIRA).

**Comment by divijvaidya** [comment]
Updated the PR with changes to NOTICE and changelog

**Comment by robertdale** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE +1

**Pull request merged**
