### PR TITLE
TINKERPOP-1641 Kerberos support for python

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1641

This PR replaces #1285.

VOTE +1

### CODE REVIEW

**Comment by vtslab** [comment]
I agree with this comment on the original PR:
"I do think the hardcoded "3.5.0-SNAPSHOT" in docker-entrypoint.sh needs to be dynamically referenced."
From the docker/gremlin-server/Dockerfile.template a GREMLIN_SERVER_VERSION variable is available from the environment. So, the offending line in docker-entrypoint.sh should read:
`
java -cp /opt/gremlin-test/gremlin-test-${GREMLIN_SERVER_VERSION}-jar-with-dependencies.jar \
`
While testing this I found that docker/gremlin_server.sh did not run and I do not understand how it ever can have worked. Anyway, docker needs absolute paths for the mounts and I think the docker run line should read:
```
ABS_PROJECT_HOME=$(dirname $(realpath $0))/..
docker run ${TINKERPOP_TEST_DOCKER_OPTS} ${REMOVE_CONTAINER} -h gremlin-server-test -v "${HOME}"/.groovy:/root/.groovy \
    -v "${HOME}"/.m2:/root/.m2 -v "${ABS_PROJECT_HOME}"/gremlin-test/target:/opt/gremlin-test -ti tinkerpop:${BUILD_TAG} ${@}
```

If you want I can put it in a PR against branch TINKERPOP-1641

**Comment by spmallette** [comment]
I've pushed the changes you suggested. Docker looks better now. 

VOTE +1

**Comment by vtslab** [comment]
Great 
VOTE +1

**Comment by spmallette** [comment]
It was suggested to me separately that we look to enhance the `Client` API as we keep just expanding its construction with new keywords. No need to do it for this PR - I've created an issue for discussion:

https://issues.apache.org/jira/browse/TINKERPOP-2382

**Comment by spmallette** [comment]
@vtslab sorry this one is still not merged - i'd like to get #1299 in first then look to merging this.

**Comment by spmallette** [comment]
I rebased this now that #1299 merged but now i'm getting failures with docker builds. need to investigate that further. the spark failures seem common now on travis for some reason...they seem to take longer than the 50 minute limit despite us not adding any additional tests recently.  probably need to look into that as well.

**Comment by spmallette** [comment]
Rebased this on master - had to add an extra commit to cover issues with the removal of the templating system for GLVs. Still have to look into the docker issues and travis/spark build problems.

**Comment by spmallette** [comment]
Docker problems seem resolved now for some reason. I wonder if I ran afoul of an out-of-date docker image. Travis failures around spark still seem spread about. Restarted some travis builds that failed.

**Pull request merged**
