### PR TITLE
TINKERPOP-2826 bump ivy to 2.5.1

### PR DESCRIPTION
**Pull request by acoady**

### CODE REVIEW

**Comment by acoady** [comment]
Can we include this in 3.6-dev and 3.5-dev for the upcoming releases?

**Review by FlorianHockmann — APPROVED** [review]
VOTE +1

> Can we include this in 3.6-dev and 3.5-dev for the upcoming releases?

Sure, it shouldn't be a problem to merge this soon and everything merged in time will be included in these releases. We also merge all PRs targeted for `3.5-dev` into `3.6-dev` and `master` so all upcoming releases will include this.

**Comment by acoady** [comment]
Can someone merge this on my behalf?

**Comment by spmallette** [comment]
sorry - we're a bit behind on PRs at the moment. thanks for submitting this.

**Pull request merged**
