### PR TITLE
TINKERPOP-1666 YAML file supplied to FileSandboxExtension can have empty staticVariableTypes

### PR DESCRIPTION
**Pull request by dpitera**
Check if variable is null to avoid NPE

If staticVariableTypes is an empty list in the YAML file, then we throw
an NPE by trying to run collectEntries() on a null object or trying to
run containsKey() on a null object.

https://issues.apache.org/jira/browse/TINKERPOP-1666

### CODE REVIEW

**Comment by spmallette** [comment]
I wonder why I never noticed this as a problem. This could be targeted at `tp32` branch, right? also would you mind pasting the URL of the JIRA into your pull request comment - we try to do that for all PRs for convenience of reviewers.

**Comment by dpitera** [comment]
Fixed all that you asked and supplied a Unit Test

**Comment by spmallette** [comment]
Next time please consider doing a `git rebase` as opposed to a `git merge` so we don't get the extra merge commit into your PR.

**Comment by dpitera** [comment]
Yeah I agree 100%-- I used the UI and didn't realize it would do it like that. I can fix manually if you'd like

**Comment by spmallette** [comment]
that would be nice if you could correct it.

**Comment by dpitera** [comment]
fixed

**Comment by spmallette** [comment]
All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Comment by twilmes** [comment]
Looks good
VOTE: +1.

**Comment by spmallette** [comment]
need one more review on this one - any committers available to help out?

**Comment by pluradj** [comment]
Docker build with `docker/build.sh -t -n -i` was successful. Code and unit tests look fine.

VOTE: +1

**Pull request merged**
