### PR TITLE
TINKERPOP-2237: Prevent exception when closing a session that doesn't exist

### PR DESCRIPTION
**Pull request by nastra**
https://issues.apache.org/jira/browse/TINKERPOP-2237

### CODE REVIEW

**Comment by spmallette** [comment]
A bit surprised we didn't see a test failure somewhere as a result of this change. travis doesn't apparently run those test. Did you happen to run:

`mvn clean install -DskipTests && mvn verify -pl gremlin-server -DskipIntegrationTests=false`

does that pass? 

I think i'll add that test variation to the travis builds.

**Comment by nastra** [comment]
I haven't run it because I was relying on the travis build actually. But running it now. Will comment later with the outcome

**Comment by nastra** [comment]
@spmallette all tests passed

**Comment by spmallette** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE +1

**Pull request merged**
