### PR TITLE
adding multi source djikstra algorithm

### PR DESCRIPTION
**Pull request by nikita15p**
Signed-off-by: nikita15p <nikita15p@gmail.com>

### CODE REVIEW

**Comment by spmallette** [comment]
thanks for offering this. here's some general comments:

1. This looks mostly like a copy/paste of the existing `ShortestPathVertexProgram` with some minor change to `collectShortestPaths()`. is that the only change? If it is, is then I think you'd want to rethink how this is implemented so that you could offer this new functionality and make better re-use of existing code.
2. For an "algorithm" I wouldn't typically be in favor of accepting a PR with just the `VertexProgram` implementation. We would want it accessible from Gremlin as we do with other algorithms which could mean a Gremlin language change (maybe?) which would in turn require some discussion. That's just my opinion though...perhaps others would have different feeling. 
3. Tests?
4. There's more administrative things to bring up (like documentation), if this were to be considered for merge, but that can all be saved for a later when the bigger items already listed are more settled.

**Comment by nikita15p** [comment]
@spmallette  thanks for comments. So this functionality offers multi source djikstra algorithm and it leverages shortestPath code...So shall I be imporing ShortestPathVertexProgram methods then?

**Comment by spmallette** [comment]
I'm not sure what you mean by:

> So shall I be imporing ShortestPathVertexProgram methods then?

**Comment by spmallette** [comment]
closing this PR as there hasn't been any activity on it. if you're still interested in it, please feel free to open a new one with the feedback provided addressed.

**Pull request closed without merging**
