### PR TITLE
TINKERPOP-1820 TravisCI: Add Gremlin.Net as job

### PR DESCRIPTION
**Pull request by jorgebay**
https://issues.apache.org/jira/browse/TINKERPOP-1820

Adds `gremlin-dotnet` integration tests to travis build as a separate job.

### CODE REVIEW

**Comment by spmallette** [comment]
interesting - the separate jobs thing is kinda neat:

https://travis-ci.org/apache/tinkerpop/builds/304649749

**Comment by jorgebay** [comment]
@spmallette Yes, the separate jobs run in parallel, so in a few minutes you can check if the module from the job is affected.

VOTE +1

**Comment by spmallette** [comment]
VOTE +1

**Comment by FlorianHockmann** [comment]
The separate jobs are really useful.

VOTE +1

**Comment by jorgebay** [comment]
Landed in `tp32` and merged into `master`.

**Pull request merged**
