### PR TITLE
TINKERPOP-1930 Remove Giraph

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1930

Build time with integration test is less than half without giraph - nice. Not much more to say.

VOTE +1

### CODE REVIEW

**Comment by dkuppitz** [comment]
I think there's more that can be removed:

```diff
diff --git a/pom.xml b/pom.xml
index ef2be4821d..ddd9167a51 100644
--- a/pom.xml
+++ b/pom.xml
@@ -582,15 +582,6 @@ limitations under the License.
                         <groupId>commons-logging</groupId>
                         <artifactId>commons-logging</artifactId>
                     </exclusion>
-                    <!-- conflicts with giraph-core (which appears to have more consistent dependencies) -->
-                    <exclusion>
-                        <groupId>org.codehaus.jackson</groupId>
-                        <artifactId>jackson-core-asl</artifactId>
-                    </exclusion>
-                    <exclusion>
-                        <groupId>org.codehaus.jackson</groupId>
-                        <artifactId>jackson-mapper-asl</artifactId>
-                    </exclusion>
                     <!-- conflict with TinkerPop tests -->
                     <exclusion>
                         <groupId>junit</groupId>
@@ -1146,7 +1137,7 @@ limitations under the License.
                                     <overview>${basedir}/docs/javadoc/overview.html</overview>
                                     <quiet>true</quiet>
                                     <sourcepath>
-                                        giraph-gremlin/src/main/java:gremlin-core/src/main/java:gremlin-driver/src/main/java:gremlin-groovy/src/main/java:gremlin-python/src/main/java:gremlin-server/src/main/java:gremlin-test/src/main/java:hadoop-gremlin/src/main/java:neo4j-gremlin/src/main/java:spark-gremlin/src/main/java:tinkergraph-gremlin/src/main/java
+                                        gremlin-core/src/main/java:gremlin-driver/src/main/java:gremlin-groovy/src/main/java:gremlin-python/src/main/java:gremlin-server/src/main/java:gremlin-test/src/main/java:hadoop-gremlin/src/main/java:neo4j-gremlin/src/main/java:spark-gremlin/src/main/java:tinkergraph-gremlin/src/main/java
                                     </sourcepath>
                                 </configuration>
                             </execution>
```

However, `docker/build.sh -d` fails with an `AbstractMethodError` in Spark, but I'm afraid that's a problem in other branches as well.

**Comment by spmallette** [comment]
i meant to come back to that pom.xml and forgot. seems ok to drop the two exclusions now that giraph is gone. didn't get any new conflicts in doing so when i built.

**Comment by dkuppitz** [comment]
Best PR ever ;)

VOTE: +1

**Comment by robertdale** [comment]
Should get a CHANGELOG entry, right?

**Comment by spmallette** [comment]
added changelog entry

**Comment by robertdale** [comment]
VOTE +1

**Comment by robertdale** [comment]
Can this be merged?

**Pull request merged**
