### PR TITLE
TINKERPOP-2432 + TINKERPOP-2439: fix bytecode toString() and fix P and TextP toString()

### PR DESCRIPTION
**Pull request by sergsalo**
Traversal class now contains toJSON() method which causes JSON.stringify() to properly serialize the Traversal object. Unit tests for bytecode serialization are also included

### CODE REVIEW

**Comment by sergsalo** [comment]
@spmallette hi, where do I add a change log?

**Comment by spmallette** [comment]
here - https://github.com/apache/tinkerpop/blob/3.4-dev/CHANGELOG.asciidoc

just add a bullet to 3.4.9 - thanks!

on a side, note i'm not sure why travis failed - i restarted the builds. i imagine it was some travis environmental timeout or something.

**Comment by spmallette** [comment]
Looking at the build failure - I sense it is because you need to update the templating system. You just need to add this change:

https://github.com/apache/tinkerpop/pull/1341/files#diff-2289ce5bddc098e63bae601f203c71b9R126-R133

here:

https://github.com/apache/tinkerpop/blob/c3a732bf302fdf7421745fd60087fa8d8970a34b/gremlin-javascript/glv/TraversalSource.template#L125

That change should solve the problem. Sorry - that's definitely not an obvious thing to do. The templating system goes away in 3.5.0.

**Comment by sergsalo** [comment]
@spmallette committed the changes. build still failed

**Comment by spmallette** [comment]
travis is so unstable - the javascript build passed so i think you might have it working right. i've re-execute the one build that failed.

**Comment by sergsalo** [comment]
@spmallette looks good.

**Comment by sergsalo** [comment]
@spmallette so, will you need to approve this PR to move forward?

**Comment by spmallette** [comment]
Our review/merge procedures require either:

1.  3 +1s from committers OR 
2. At least a single +1 from a committer and 7 day open wait period for comment

https://tinkerpop.apache.org/docs/current/dev/developer/#rtc

i will look at this in more detail tomorrow (and hopefully @jorgebay will have time to get a second look) but I sense you have things in pretty good order now.

**Comment by sergsalo** [comment]
@spmallette I have found one more bug TINKERPOP-2439. Should I just fix in the same PR? (I will add one more unit test and changelog)

**Comment by spmallette** [comment]
It is fine if you add to this one. Sure. Thanks for continuing to find/fix things.

**Comment by spmallette** [comment]
It looks like you got a mix of commits in your pull request now - do you mind cleaning up your commit history a bit so that it just has you commits in it?

**Comment by sergsalo** [comment]
@spmallette yes, will do.

**Comment by sergsalo** [comment]
@spmallette I removed the mix of commits. There are conflicts that you should resolve from your side i think .

**Comment by spmallette** [comment]
A CHANGELOG conflict is not a big deal - easy for either of us to resolve (we just don't get a travis run to look at when there is a conflict on the PR, but that's fine, i can build locally on merge). I will merge tomorrow unless we get two more VOTEs today.

VOTE +1

**Comment by spmallette** [comment]
I needed to add in this commit as the template changed again (can't wait until 3.5.0 when we don't have to fuss with that system anymore and changes don't have to go through that) - edaa482b0e262ad054491ab51379ab4bccdc06a1

other than that, this one is all settled. thanks @sergsalo for taking care of this one and carrying it all the way through with all the changes we requested. hope to see you on future contributions 🙂

**Pull request merged**
