### PR TITLE
TINKERPOP-1731 Build for .NET working in docker

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1731

Build seems to work in full now.

All tests pass with `docker/build.sh -t -n -i`

VOTE +1

### CODE REVIEW

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by jorgebay** [comment]
I've got a failure on Gremlin Python:

```
[INFO] --- maven-antrun-plugin:1.8:run (setup-py-env) @ gremlin-python ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
     [copy] Copying 44 files to /usr/src/tinkerpop/gremlin-python/target/python3
     [copy] Copying 44 files to /usr/src/tinkerpop/gremlin-python/target/python2
     [copy] Copying 44 files to /usr/src/tinkerpop/gremlin-python/target/python-packaged
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache TinkerPop .................................. SUCCESS [3:13.218s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [30.870s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [1:04.724s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [5.845s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [6:45.098s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [3.929s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [6:09.785s]
[INFO] Apache TinkerPop :: Gremlin Benchmark ............. SUCCESS [7.064s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [1:42.859s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [21:10.620s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [16:43.687s]
[INFO] Apache TinkerPop :: Gremlin Python ................ FAILURE [1:11.484s]
[INFO] Apache TinkerPop :: Gremlin.Net ................... SKIPPED
[INFO] Apache TinkerPop :: Gremlin.Net - Source .......... SKIPPED
[INFO] Apache TinkerPop :: Gremlin.Net - Tests ........... SKIPPED
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SKIPPED
[INFO] Apache TinkerPop :: Spark Gremlin ................. SKIPPED
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SKIPPED
[INFO] Apache TinkerPop :: Gremlin Console ............... SKIPPED
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SKIPPED
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SKIPPED
[INFO] Apache TinkerPop :: Archetype - Server ............ SKIPPED
[INFO] Apache TinkerPop :: Archetype - DSL ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59:06.197s
[INFO] Finished at: Fri Sep 22 10:39:06 UTC 2017
[INFO] Final Memory: 137M/338M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (setup-py-env) on project gremlin-python: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "virtualenv" (in directory "/usr/src/tinkerpop/gremlin-python/target/python2"): error=2, No such file or directory
[ERROR] around Ant part ...<exec failonerror="true" dir="/usr/src/tinkerpop/gremlin-python/target/python2" executable="virtualenv">... @ 13:107 in /usr/src/tinkerpop/gremlin-python/target/antrun/build-main.xml
```

**Comment by jorgebay** [comment]
Maybe I have to remove the previous tinkerpop:base image?

**Comment by jorgebay** [comment]
Recreating `tinkerpop:base`now...

**Comment by spmallette** [comment]
yes - you gotta remove the old image

**Comment by jorgebay** [comment]
dotnet tests pass on docker 🎉 

Relevant lines:

```
Test run for /usr/src/tinkerpop/gremlin-dotnet/test/Gremlin.Net.IntegrationTest/bin/Release/netcoreapp1.0/Gremlin.Net.IntegrationTest.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.8446945]   Discovering: Gremlin.Net.IntegrationTest
[xUnit.net 00:00:01.0599920]   Discovered:  Gremlin.Net.IntegrationTest
[xUnit.net 00:00:01.1216217]   Starting:    Gremlin.Net.IntegrationTest
[xUnit.net 00:00:03.0767841]   Finished:    Gremlin.Net.IntegrationTest

Total tests: 77. Passed: 77. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 4.1080 Seconds


Build started, please wait...
Build completed.

Test run for /usr/src/tinkerpop/gremlin-dotnet/test/Gremlin.Net.UnitTest/bin/Release/netcoreapp1.0/Gremlin.Net.UnitTest.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.7192188]   Discovering: Gremlin.Net.UnitTest
[xUnit.net 00:00:00.9493505]   Discovered:  Gremlin.Net.UnitTest
[xUnit.net 00:00:01.0271298]   Starting:    Gremlin.Net.UnitTest
[xUnit.net 00:00:02.1334540]   Finished:    Gremlin.Net.UnitTest

Total tests: 131. Passed: 131. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.9851 Seconds
```

VOTE: +1

**Pull request merged**
