### PR TITLE
Use error-prone compiler

### PR DESCRIPTION
**Pull request by leventov**
See http://errorprone.info/. Fixes a number of bugs.

This is just first step; maintainers of this project are encouraged to enable more checks eventually, e. g. "Experimental ERROR" patterns from here: http://errorprone.info/bugpatterns

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for taking a look at our build. Unfortunately, this kind of change can't really be considered as part of just a pull requeswt. we'd need significant community discussion about (1) whether or not we want our build altered with more tooling at this stage of its development (2) if we did want more tooling, we'd need to discuss the right tool for the job (it could be "errorprone", it might not be - i'm sure people have lots of opinion on this topic) (3) if we did actually choose one or more, then we'd need to decide which checks we would enable. Anyway, if you'd like to lead that discussion to get a change like this in, please begin a DISCUSS thread on our dev mailing list. Thanks again.

**Comment by spmallette** [comment]
Thanks again for taking a look at our build and participating in the community discussion around this change, but given the disposition of the thread, it doesn't look like we'll be taking this approach:

https://lists.apache.org/thread.html/b8abc4d43028b24e862b893078ec012803dc47db464f40ae0e7dbee8@%3Cdev.tinkerpop.apache.org%3E

**Comment by leventov** [comment]
Could you reopen this PR? I'm going to leave out the build changes and keep only the code changes.

**Comment by leventov** [comment]
@spmallette is it considerable?

**Comment by spmallette** [comment]
sorry - i didn't see your reply earlier i the week. i think this PR even without the build changes had problems. the PR branch wasn't building I don't think (i seem to remember @robertdale bringing that up at various points). was all that fixed? 

thus far we've only talked about the build changes as I thought that was the primary point of the PR so i never bothered to comment much on the changes themselves. since you ask about that now, i'd say that they are hard to evaluate as they have been submitted. Because it is one giant PR, I don't understand the reasoning for these changes. You do have some detailed comments about the changes to `TraversalStrategy` which is nice, but that body of change is terrifying to be honest. It wouldn't surprise me if that was the source of the build problems.  That sort of change to that important area of code would require its own pull request and could require a discussion on the dev list. 

So, reopen this PR? - I'd say "no". I'd say that if you feel really strongly about these changes for some reason, then they should be broken apart into new individual PRs so that they can each be evaluated on their own merit. As a reviewer (and you need 3 committers to vote +1 for us to merge), personally I'd be much happier to see PRs that do more than add generics or reformat imports because some tool said to do it. Like, if you truly have a much better way to sort traversal strategies - wow...that would be awesome! Or if traversal strategy application was bug prone and that tool your using uncovered that and it fixed a subtle problem no one ever noticed - excellent! But, please frame your PR in that fashion so that we understand what we're exactly evaluating. Organizing your work that way will help immensely on our side.

Hope that helps frame my opinion on this. I'm sure someone else will chime in if they think something different. Thanks!

**Pull request closed without merging**
