### PR TITLE
Export Result interface

### PR DESCRIPTION
**Pull request by good41898**
The `Result` struct does not allow for any assigning of data, which makes it impossible to mock out for testing. While the `ResultSet` interface and its methods can be mocked out, they must match the original function signature, and return the `Result` type. Since you cannot assign to the unexported `Result` type, it is not possible to mock out returning data from the various methods of `ResultSet`.

### CODE REVIEW

**Comment by good41898** [comment]
https://issues.apache.org/jira/browse/TINKERPOP-2785

**Comment by xiazcy** [comment]
Hi, @good41898, thank you for raising the issue. We will take a look. 
Also a quick note before diving into the issue, please make sure all tests pass locally with your changes. As it currently stands, just exporting the field in the `Result` struct without changing any reference to it will generate errors. Thanks!

**Comment by good41898** [comment]
Thanks @xiazcy ! I was able to successfully run unit tests locally for Result and ResultSet packages, but am running into connection issues with the local gremlin server while running `./run.sh 3.6.1` even though I have confirmed both the gremlin server container and integration test container are up and running, and on the same docker network. Thanks

**Comment by lyndonbauto** [comment]
@good41898 Hi there, thanks for using the Golang driver, cool to see people are putting it into things now.

First off, did you need some help with running the tests? If you need more assistance there feel free to jump into the TinkerPop Discord and send us some more details, you can @ myself or yang to get our attention quicker.

On the note of this code. I am unsure why this is required. The typical technique from my understanding of Golang (which I will admit is minimal) is to mock by making your own interface, for example: https://github.com/apache/tinkerpop/blob/master/gremlin-go/driver/gorillaTransporter_test.go#L35-L66

Please correct my if I am wrong in my understanding. 

Anyway I will approve your workflow to run since @xiazcy has suggested it might create some errors.

**Comment by lyndonbauto** [comment]
Looks like tests are passing. I am OK with moving this through if there is an actual need, just need you to get back to me on this part

> On the note of this code. I am unsure why this is required. The typical technique from my understanding of Golang (which I will admit is minimal) is to mock by making your own interface, for example: https://github.com/apache/tinkerpop/blob/master/gremlin-go/driver/gorillaTransporter_test.go#L35-L66

before we proceed @good41898

**Comment by good41898** [comment]
You are correct that the typical technique for mocking is by making your own interface! 

To give an example of the issue, I have abstracted the gremlin-go driver into an interface like this:

`GremlinGoDriver interface {
   Submit(traversalString string) (gremlingo.ResultSet, error)
   Close()
}`

Which contains the two methods of the driver that I use. While unit testing, I am able to mock out any methods (like the Submit() and Close() method) as long as the function signatures for the mocked methods match the signatures of the actual methods. Where I am running into issues is when trying to mock returned data from a `ResultSet` object. I am able to create a new struct containing the result set so I can mock those methods (like the ResultSet.All() method) as well, like this:

```
type MockResultSet struct {
  ResultSet
 }
 
 func (m MockResultSet) All() ([]*Result, error) {
    var res []*Result
    return  res
 }
```
  
However, since the function signatures must match, this mocked All() method must return a Result object, which I cannot assign data to as the result field is non-exported.

Let me know if this is helpful/ makes sense. Thanks.

**Comment by good41898** [comment]
closing pull request, will open a new one based off of `3.5-dev`

**Pull request closed without merging**
