### PR TITLE
TINKERPOP-1391 issue with where filter

### PR DESCRIPTION
**Pull request by dkuppitz**
Enclose filter steps and side-effect steps in `RangeByIsCountStrategy` when `NotStep` is used to wrap part of the traversal.

VOTE: +1

### CODE REVIEW

**Comment by spmallette** [comment]
It looks like the code for this is the same as in the PR for tp31, but the commit hashes are different. is this one of those cherry-pick situations you were referencing in hipchat? I suspect that this will merge cleanly if you re-issue the PR with:

```text
git checkout TINKERPOP-1391-master
git reset --hard origin/master
git merge TINKERPOP-1391
git push origin TINKERPOP-1391-master --force
```

**Comment by dkuppitz** [comment]
Right, this one was cherry-picked. But now, after a reset, a merge and a forced push, the commit hashes are still different.

**Comment by spmallette** [comment]
All tests pass with `docker/build.sh -t -i`

VOTE +1

**Comment by okram** [comment]
VOTE +1.

**Pull request merged**
