### PR TITLE
TINKERPOP-1420 Removal of previously deprecated gremlin-groovy classes/methods

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1420

While this commit is bound to TINKERPOP-1420 it actually also covers TINKERPOP-1283, TINKERPOP-1040 and TINKERPOP-833 which are all "deprecation removal" type tickets. The removed class/methods are all pretty "low-level" for the average user to be using in their code so of all the deprecation we have this one isn't a big deal for removal.

Builds nicely with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`. Manually tested `bin/gremlin.sh script.groovy` no longer works and that `-e` is required - all good.

VOTE +1

### CODE REVIEW

**Comment by dkuppitz** [comment]
`docker/build.sh -t -i -n` fails for me with:

```
Tests run: 490, Failures: 0, Errors: 1, Skipped: 54, Time elapsed: 32.5 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.groovy.jsr223.RemoteGraphGroovyTranslatorProcessStandardTest
g_V_repeatXunionXoutXknowsX_groupXaX_byXageX__outXcreatedX_groupXbX_byXnameX_byXcountXX_groupXaX_byXnameXX_timesX2X_capXa_bX(org.apache.tinkerpop.gremlin.process.traversal.step.sideEffect.GroupTest$Traversals)  Time elapsed: 0.181 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.apache.tinkerpop.gremlin.process.AbstractGremlinProcessTest.checkSideEffects(AbstractGremlinProcessTest.java:99)
	at org.apache.tinkerpop.gremlin.process.traversal.step.sideEffect.GroupTest.g_V_repeatXunionXoutXknowsX_groupXaX_byXageX__outXcreatedX_groupXbX_byXnameX_byXcountXX_groupXaX_byXnameXX_timesX2X_capXa_bX(GroupTest.java:360)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	...
```

I restarted it, but a second attempt usually only "fixes" performance related issues.

**Comment by spmallette** [comment]
something weird is going on. i did a `docker/build.sh -t -i -n` on this branch and it works fine. but i can't get #457 to build with that given repeated failures in spark.  i wonder what is going on

**Comment by spmallette** [comment]
Took three tries on #457 and then finally built. Not sure what's going on.

**Comment by dkuppitz** [comment]
So weird. Build succeeded with `docker/build.sh -t -i -n`  after I've rebuilt my containers and removed the `.glv` file from my `gremlin-python` directory.

VOTE: +1

**Comment by spmallette** [comment]
I've had three goods builds in a row with docker now on this branch. I also cleared my containers/images and it's been good since.

**Comment by okram** [comment]
Huh. Cool. Are we removing deprecations for 3.3.0? If so, should I be doing similar things in the "process" areas of the codebase?

VOTE +1.

**Comment by spmallette** [comment]
3.3.0 has been discussed as one for breaking changes so I think we should come away with a release that is free of deprecation if we can. I think we should just be methodical about it and not throw in too many breaks at once (i.e. per milestone release). That's why i started with easy stuff that probably won't break anyone at all. I have a few more like that.

**Pull request merged**
