### PR TITLE
Added JitPack Maven repository to Grape configuration

### PR DESCRIPTION
**Pull request by szarnyasg**
https://issues.apache.org/jira/browse/TINKERPOP-1430

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks @szarnyasg 

@dkuppitz how has this worked along the way? is it because we had jbcrypt in our local .m2?

**Comment by robertdale** [comment]
I would say yes and probably through building the project.  I had to add the repo to my own project pom. That updates my local .m2 repo. Once that has it, grapes can pull from there.

**Comment by dkuppitz** [comment]
Hmm, good question. I'm not an expert when it comes to dependency management, but it sounds like a reasonable explanation to me. However, from time to time I tend to delete my local .m2 directory, so it's a bit surprising that I never ran into this issue.

**Comment by robertdale** [comment]
Do you also clean your groovy/grapes dir?  artifacts will be copied there from maven. afterwards, it won't reference the maven artifacts unless they are also missing from grapes.

**Comment by dkuppitz** [comment]
Rarely. But here's another thing: The Docker build always starts with a clean environment - no .m2, no grapes - and it always worked for me.

**Comment by robertdale** [comment]
Ok. Didn't notice it mentioned docker and I can't speak to that. However, it is very repeatable on other systems.  Given no other configuration...
```
rm -rf ~/.groovy
rm -rf ~/.m2
$ ./bin/gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :install org.apache.tinkerpop neo4j-gremlin 3.2.1
==>Error grabbing Grapes -- [unresolved dependency: com.github.jeremyh#jBCrypt;jbcrypt-0.4: not found]
gremlin> 
```

**Comment by szarnyasg** [comment]
Closed: not a real issue, refer to the docs in http://tinkerpop.apache.org/docs/current/reference/#gremlin-applications.

**Pull request closed without merging**
