### PR TITLE
TINKERPOP-1249 Add keep-alive functionality to websockets Java Driver

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1249

If a connection goes idle, the driver will periodically send a ping to the server to keep the connection alive. 

All good with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`. Also ran some manual tests and did some memory profiling of the driver to make sure there were no leaks.

VOTE +1

### CODE REVIEW

**Comment by robertdale** [comment]
Tested a clean console build with 3.2.2 server.  Pinging works as expected.  Closing each Client, a Cluster, and ':remote close' does stop pinging as expected.

Not sure what the expected behavior is here but this does not stop pinging after close. I had expected it to work like Client.  Instead the Cluster must be closed.
```
cluster = Cluster.open('conf/remote-objects.yaml')
rem = DriverRemoteConnection.using(cluster, 'g')
g = EmptyGraph.instance().traversal().withRemote(rem)
g.V()
rem.close()
```

**Comment by k4rthikr** [comment]
How do I know that pings are happening in the background? In other words, how do I test this?

**Comment by robertdale** [comment]
Use your favorite packet sniffer.  I used tcpdump.

**Comment by spmallette** [comment]
@robertdale thanks for testing that. If you pass in your own `Cluster`, then the `DriverRemoteConnection`, expects you to manage it. In this way, a `Cluster` can be shared.

**Comment by robertdale** [comment]
Yup, there it is right there in the javadoc:  When close() is called, the Cluster is left open for the caller to close.

**Comment by dkuppitz** [comment]
`docker/build.sh -t -i -n` succeeded.

VOTE: +1

**Comment by PommeVerte** [comment]
VOTE +1 I get the pinging as well. Looks good.

**Comment by cjoftheweb** [comment]
Why does this wait until a connection is written to before it schedules the keepAliveFuture? Is there some other mechanism to keep connections alive before they've been written to?

**Comment by spmallette** [comment]
@cjoftheweb if there was a reason for that, i don't recall what it was. i suppose that if keep-alive is enabled it should just start doing its work after the websocket handshake is established.

**Pull request merged**
