### PR TITLE
Generate constructor to use DSL with remote connection

### PR DESCRIPTION
**Pull request by thirstycrow**
https://issues.apache.org/jira/browse/TINKERPOP-2276

### CODE REVIEW

**Comment by spmallette** [comment]
it looks like this is a really good bug fix. what kind of error do you get without this change? is it a reflection error?

I'd ask that you please do make the following additional changes:

1. rebase this change on the `tp34` branch (note that we are currently releasing 3.4.3 so rebasing will put you on that version rather than "-SNAPSHOT" - you may wish to bump to 3.4.4-SNAPSHOT or wait until I do it later this week. note that we won't be able to merge this until `tp34` is re-opened for development after release is complete).
2. add a test to Gremlin Server that ensures DSLs work with your newly added constructor and `AnonymousTraversalSource`. if you base your new test case on [AbstractGremlinServerIntegrationTest](https://github.com/apache/tinkerpop/blob/2f6b2a7adda5c498a8d318197208d6f84d5cbe5d/gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java) you will get a running Gremlin Server instance you can establish your connection to
3. Please add a CHANGELOG entry for your fix (again, you may wish to wait until we bump back to "-SNAPSHOT" before doing this so that the new version is setup and templated for you.

Thanks for taking the time to provide this fix.

**Comment by thirstycrow** [comment]
Hi, @spmallette.

An InvocationTargetException like the following one will be throw, if the constructor was not generated for the traversal source class.

I added a test for this. I will do the rebase and update the CHANGELOG once the `tp34` branch is bumped to 3.4.4-SNAPSHOT.

```
java.lang.reflect.InvocationTargetException
	at org.apache.tinkerpop.gremlin.process.traversal.dsl.GremlinDslProcessorTest.shouldCompileRemoteDslTraversal(GremlinDslProcessorTest.java:87)
Caused by: java.lang.IllegalStateException: org.apache.tinkerpop.gremlin.process.traversal.dsl.SocialTraversalSource.<init>(org.apache.tinkerpop.gremlin.process.remote.RemoteConnection)
	at org.apache.tinkerpop.gremlin.process.traversal.dsl.GremlinDslProcessorTest.shouldCompileRemoteDslTraversal(GremlinDslProcessorTest.java:87)
Caused by: java.lang.NoSuchMethodException: org.apache.tinkerpop.gremlin.process.traversal.dsl.SocialTraversalSource.<init>(org.apache.tinkerpop.gremlin.process.remote.RemoteConnection)
	at org.apache.tinkerpop.gremlin.process.traversal.dsl.GremlinDslProcessorTest.shouldCompileRemoteDslTraversal(GremlinDslProcessorTest.java:87)
```

**Comment by spmallette** [comment]
The tp34 has been re-opened for development and is set to 3.4.4-SNAPSHOT. Please feel free to rebase now.

**Comment by spmallette** [comment]
Note that Travis is failing and it seems related to this change. Could you please take a look at that?

**Pull request merged**
