### PR TITLE
TINKERPOP-1264 Improve BLVP docs

### PR DESCRIPTION
**Pull request by dkuppitz**
Added a warning message for BLVP.

### CODE REVIEW

**Comment by okram** [comment]
VOTE +1. I think this could have been a CTR as its a doc update that provides more information.

**Comment by dkuppitz** [comment]
Don't vote if you think it's a CTR case :). Now we need one more.

Here's my: +1

**Comment by spmallette** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
Merged into `tp31/` and `master/`.

**Pull request merged**
