### PR TITLE
TINKERPOP-1319: several FeatureRequirement annotations are incorrect

### PR DESCRIPTION
**Pull request by pluradj**
https://issues.apache.org/jira/browse/TINKERPOP-1319

### CODE REVIEW

**Comment by pluradj** [comment]
`mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false` runs cleanly.

VOTE: +1

**Comment by spmallette** [comment]
@pluradj any reason you have this in your fork? do you mind creating a TinkerPop repo branch and merging to that then re-issuing the PR from there?

**Comment by pluradj** [comment]
@spmallette because I find myself in GitHub more often than ASF git. I'll close this and reopen a new PR.

**Comment by spmallette** [comment]
ok - it wasn't a big deal - i could have just merged your stuff into a local branch and tested.

**Pull request closed without merging**
