### PR TITLE
Bump logback version to 1.2.9 or greater

### PR DESCRIPTION
**Pull request by simonz-bq**
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2746

### CODE REVIEW

**Comment by spmallette** [comment]
logback version is defined in the root pom.xml in `<dependencyManagement>`:

https://github.com/apache/tinkerpop/blob/master/pom.xml#L822-L826

as a result, i don't think you need to add the `<version>` to all the pom.xml individually.

**Comment by simonz-bq** [comment]
> logback version is defined in the root pom.xml in `<dependencyManagement>`:
> 
> https://github.com/apache/tinkerpop/blob/master/pom.xml#L822-L826
> 
> as a result, i don't think you need to add the `<version>` to all the pom.xml individually.

The Tinkerpop pom.xml is complex so I can't say with certainty if it's necessary.

My thought process is that if you build using the main pom.xml, then the dependency will be grabbed based on the version specified, and therefore satisfies the dependency requirement of the individual pom.xml when those dependencies are resolved.

However, if someone were to modularly use the individual maven projects as a standalone, I had a concern that then the dependency would not enforce a non-vulnerable versioning, hence why I added it.

If someone can confirm that this is not an issue, then I think removing the added `<version`> to the individual pom is good.

**Comment by spmallette** [comment]
you can remove it. the point of `<dependencyManagement>` is to centralize dependency definitions so you don't need to repeat yourself throughout the sub-modules. you should be able to prove it to yourself by doing a `mvn dependency:tree -pl <sub-module>` and check the logback version you find there.

>  if someone were to modularly use the individual maven projects as a standalone

just fyi, they would have to make a lot of changes to the a sub-project pom to get it to work in this fashion, so i would hope they would just skip trying to do that.

**Comment by lyndonbauto** [comment]
VOTE+1 I will merge this through sometime today.

**Pull request merged**
