### PR TITLE
TINKERPOP-1529 LazyBarrierStrategy is too aggressive (variant 2)

### PR DESCRIPTION
**Pull request by dkuppitz**
https://issues.apache.org/jira/browse/TINKERPOP-1529

This fixes a long-term bug that was introduced when `LazyBarrierStrategy` and `PathRetractionStrategy` started adding `NoOpBarrierSteps`. The bug prevented a traversal from inspecting intermediate side-effect results produced by non-barrier `SideEffectSteps` like `StoreStep`.

In contrast to https://github.com/apache/tinkerpop/pull/484 this PR extends the `Traversal` interface (adds support for metadata) and solves the issue using a new traversal strategy called `NoBarrierStrategy`.

### CODE REVIEW

**Comment by okram** [comment]
Why add methods to `Traversal`? Why add a new `TraversalStrategy`? To solve this problem in particular, why not just "walk right" and if you see a "lazy side-effect" like `StoreStep`, then turn trigger a flag in `LazyBarrierStrategy` to not apply barriers. You can then turn back on the flag if you there are no more steps that introspect into the side-effect.

For example:

`g.V().out().out().store('a').out().out().cap('a').out().out()`

This would compile to:

`g.V().out().barrier().out().barrier().store('a').out().out().cap('a').barrier().out().barrier().out()`

**Comment by dkuppitz** [comment]
Because it's more complex then that. Example:

```
g.V().as("a").out().store("a").in().sideEffect(<access "a">).groupCount().unfold().sideEffect(<access "a">)...
```

In the first access to "a" we expect to get intermediate result. The second time we expect the final "a".

**Comment by okram** [comment]
Thats fine, just assume that `sideEffect(access a)` is never "the final."

**Comment by dkuppitz** [comment]
Well, what you're saying is "put all the logic into `LazyBarrierStrategy`". But what about `PathRetractionStrategy`? Same rules apply there - copy the code there as well? And if we add another strategy that adds smart `barrier()`'s, copy the code again?

**Comment by dkuppitz** [comment]
The only change I would like to do: rename "frozen steps" to "lazy steps" as they're not completely untouchable for all other strategies, it's really just about `barrier()` placements.

**Comment by okram** [comment]
What happens when people do an explicit `barrier()` in their code? e.g. `store("a").barrier()` ?

**Comment by dkuppitz** [comment]
That's fine. It's like with any other `BarrierStep` - the strategy then assumes that intermediate results are no longer needed and stops marking steps as `lazy`.

**Comment by dkuppitz** [comment]
Here's an example that shows how it produces the expected result and still tries to use `barrier()`'s as often as possible:

```
gremlin> g = TinkerFactory.createModern().traversal()
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], standard]
gremlin> g.V().store("a").both().sideEffect(select("a").sideEffect {println "Expect Intermediate: " + it.get()}).barrier().
......1>   out().out().sideEffect(select("a").sideEffect {println "Expect Final: " + it.get()})
Expect Intermediate: [v[1]]
Expect Intermediate: [v[1]]
Expect Intermediate: [v[1]]
Expect Intermediate: [v[1], v[2]]
Expect Intermediate: [v[1], v[2], v[3]]
Expect Intermediate: [v[1], v[2], v[3]]
Expect Intermediate: [v[1], v[2], v[3]]
Expect Intermediate: [v[1], v[2], v[3], v[4]]
Expect Intermediate: [v[1], v[2], v[3], v[4]]
Expect Intermediate: [v[1], v[2], v[3], v[4]]
Expect Intermediate: [v[1], v[2], v[3], v[4], v[5]]
Expect Intermediate: [v[1], v[2], v[3], v[4], v[5], v[6]]
Expect Final: [v[1], v[2], v[3], v[4], v[5], v[6]]
==>v[5]
==>v[5]
==>v[5]
Expect Final: [v[1], v[2], v[3], v[4], v[5], v[6]]
==>v[3]
==>v[3]
==>v[3]
gremlin> g.V().store("a").both().sideEffect(select("a").sideEffect {println "Expect Intermediate: " + it.get()}).barrier().
......1>   out().out().sideEffect(select("a").sideEffect {println "Expect Final: " + it.get()}).explain()
==>Traversal Explanation
===========================================================================================================================================================================================================================================
Original Traversal                 [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]

ConnectiveStrategy           [D]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
MatchPredicateStrategy       [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
InlineFilterStrategy         [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
IncidentToAdjacentStrategy   [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
AdjacentToIncidentStrategy   [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
FilterRankingStrategy        [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
RangeByIsCountStrategy       [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
RepeatUnrollStrategy         [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
PathRetractionStrategy       [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), VertexStep(OUT,vertex)
                                      , TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
LazyBarrierStrategy          [O]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), NoOpBarrierStep(2500),
                                       VertexStep(OUT,vertex), NoOpBarrierStep(2500), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
TinkerGraphCountStrategy     [P]   [GraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), NoOpBarrierStep(2500),
                                       VertexStep(OUT,vertex), NoOpBarrierStep(2500), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
TinkerGraphStepStrategy      [P]   [TinkerGraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), NoOpBarrierStep(
                                      2500), VertexStep(OUT,vertex), NoOpBarrierStep(2500), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
ProfileStrategy              [F]   [TinkerGraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), NoOpBarrierStep(
                                      2500), VertexStep(OUT,vertex), NoOpBarrierStep(2500), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
StandardVerificationStrategy [V]   [TinkerGraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), NoOpBarrierStep(
                                      2500), VertexStep(OUT,vertex), NoOpBarrierStep(2500), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]

Final Traversal                    [TinkerGraphStep(vertex,[]), StoreStep(a), VertexStep(BOTH,vertex), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)]), NoOpBarrierStep, VertexStep(OUT,vertex), NoOpBarrierStep(
                                      2500), VertexStep(OUT,vertex), NoOpBarrierStep(2500), TraversalSideEffectStep([SelectOneStep(a), LambdaSideEffectStep(lambda)])]
```

**Comment by okram** [comment]
```
gremlin> g.V().barrier().store('a').sideEffect(select('a')).explain()
==>Traversal Explanation
==================================================================================================================================================================
Original Traversal                 [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a)])]

ConnectiveStrategy           [D]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a)])]
NoBarrierStrategy            [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a)])]
RepeatUnrollStrategy         [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a)])]
MatchPredicateStrategy       [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a)])]
PathRetractionStrategy       [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
InlineFilterStrategy         [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
IncidentToAdjacentStrategy   [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
AdjacentToIncidentStrategy   [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
FilterRankingStrategy        [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
RangeByIsCountStrategy       [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
LazyBarrierStrategy          [O]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
TinkerGraphCountStrategy     [P]   [GraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
TinkerGraphStepStrategy      [P]   [TinkerGraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
ProfileStrategy              [F]   [TinkerGraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
StandardVerificationStrategy [V]   [TinkerGraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]

Final Traversal                    [TinkerGraphStep(vertex,[]), NoOpBarrierStep, StoreStep(a), TraversalSideEffectStep([SelectOneStep(a), NoOpBarrierStep(2500)])]
gremlin>
```
`NoBarrierStep` doesn't seem to do anything.... ?

**Comment by okram** [comment]
I do like `Traversal.metadata()`. However, I think that metadata should be stored at the root traversal only. Thus, its a global blackboard. Next, given that its an `Admin` method, it should just use standard Java method naming -- `Traversal.getMetadata()`, `Traversal.setMetadata()`.  If the traversal is NOT the root, then it walks the tree to get the metadata from the root.

If we do the metadata-thang in this ticket, we should update all the MARKER strategies -- AdjacentToIncident and SubgraphStrategy. (prolly some other?).

I think your `NoBarrier` work should really just be inlined into `LazyBarrierStragegy` and `PathRetractionStrategy`. Checkout how `LazyBarrierStrategy` has this notion of labeled paths and path processor ... its a "switch" to say whether or not to barrier.

**Comment by spmallette** [comment]
This closed automatically after the renaming of the `tp3*` branches to the `3.x-dev` pattern.

**Pull request closed without merging**
