### PR TITLE
TINKERPOP-1880 Sign assembly on Linux and macOS

### PR DESCRIPTION
**Pull request by jorgebay**
With the latest .NET Core SDK (2.1.101), its now possible to sign assemblies from Linux and macOS.

We should update our own local installation to use 2.1.101+ to run the .NET test locally.
The Gremlin.NET package still targets .NET Standard 1.3, there isn't any change for our users.

VOTE +1

### CODE REVIEW

**Comment by spmallette** [comment]
could you please update the dev docs with the .NET core version required now:

https://github.com/apache/tinkerpop/blob/7d751116408ff078503066bd61639e2f7f70f95c/docs/src/dev/developer/development-environment.asciidoc#dotnet-environment

Other than that, this is good stuff - just in time for release: VOTE +1

**Comment by jorgebay** [comment]
Nice catch @spmallette, I've fixed it.

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by jorgebay** [comment]
Thanks @dkuppitz for the Dockerfile update!

**Comment by jorgebay** [comment]
I've merged it into `tp32`, `tp32` into `tp33` and `tp33` into `master`.

This pull request shown master being the base branch when it was `tp32`.

**Pull request merged**
