### PR TITLE
Fixed and simplified 'language not supported' formatting.

### PR DESCRIPTION
**Pull request by joshsh**
See also closed PR https://github.com/apache/tinkerpop/pull/502/commits/5e6e93ee87992cc61b23509c056d434310e6385e

### CODE REVIEW

**Comment by spmallette** [comment]
@joshsh if you could please re-target this at tp31 I can get this merged. no need for vote on this one i don't think.

**Comment by joshsh** [comment]
@spmallette, is this appropriate for tp32 now that tp31 has been merged in?  I didn't know why tp31 was still an active development branch.

**Comment by spmallette** [comment]
We maintain three separate release branches - the 3.1.x line of code (currently 3.1.6) that is on tp31. tp32 is 3.2.x (currently 3.2.4) and master is 3.3.x (currently looking at its first release for 3.3.0). We commit changes to the appropriate release branches then merge tp31 -> tp32 -> master.

**Comment by spmallette** [comment]
@joshsh think you might come back to this pull request any time soon?

**Comment by joshsh** [comment]
Sure. Is tp31 still the right branch for it, @spmallette?

**Comment by spmallette** [comment]
yes - this is fine for tp31 - thanks

**Comment by joshsh** [comment]
Closing this PR.  See the replacement, https://github.com/apache/tinkerpop/pull/543

**Pull request closed without merging**
