### PR TITLE
TINKERPOP-1605 gremlin-console 3.2.3 -e can no longer take paths relative to current working directory

### PR DESCRIPTION
**Pull request by dkuppitz**
https://issues.apache.org/jira/browse/TINKERPOP-1605

```
daniel@cube /tmp $ ls *.groovy
test.groovy

daniel@cube /tmp $ /projects/apache/tinkerpop/bin/gremlin.sh -e test.groovy 
2
4
6

daniel@cube /tmp $ /projects/apache/tinkerpop/bin/gremlin.sh -e test2.groovy 
Gremlin file not found at [test2.groovy].

daniel@cube /tmp $  /projects/apache/tinkerpop/bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> graph = TinkerGraph.open()
==>tinkergraph[vertices:0 edges:0]
gremlin> graph.io(graphml()).readGraph('data/grateful-dead.xml')
==>null
gremlin> g = graph.traversal()
==>graphtraversalsource[tinkergraph[vertices:808 edges:8049], standard]
```

VOTE: +1

### CODE REVIEW

**Comment by spmallette** [comment]
I did some manual tests - seems to work nicely - VOTE +1

**Comment by okram** [comment]
VOTE +1

**Comment by okram** [comment]
Actually, can you add a test case for this so we know it doesn't break again in the future?

**Comment by dkuppitz** [comment]
I don't know. The fix relies on a change in `gremlin.sh`. Is that testable?

**Comment by spmallette** [comment]
i was trying to think how we could do it but didn't really come up with anything. we really don't have any tests for `Console` right now that I know of - not sure how we would reasonably do that with JUnit.

**Comment by dkuppitz** [comment]
Same here. I can't think of a way to test `gremlin.sh`. The script requires that the project was built, but tests can be run without building the project upfront. Going to merge this PR for now.

**Comment by robertdale** [comment]
Isn't there a distribution verification that does tests?  I know it's post-build, but that's better than nothing.

**Comment by dkuppitz** [comment]
Oh, that's a good idea! I will add that.

**Comment by dkuppitz** [comment]
Done. We already use `validate-distribution.sh` to test script evaluations, so it was easy to another test.

https://github.com/apache/tinkerpop/commit/62785dcb686be7d56bf207a0ef4279f912cbe41e

**Pull request merged**
