### PR TITLE
Minor word and link cleanup

### PR DESCRIPTION
**Pull request by robertdale**
Fixed spelling and links.

### CODE REVIEW

**Comment by spmallette** [comment]
This is a nice body of fixes @robertdale - thanks for this. I suppose a good number of these fixes would be good patches to the tp31 branch.  Could this PR be re-targetted at tp31 without too much bother on your end? thoughts?

**Comment by robertdale** [comment]
I added a separate pull request because of some differences in 3.1.

**Comment by spmallette** [comment]
VOTE +1

**Comment by PommeVerte** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
