### PR TITLE
TINKERPOP-1742 RangeByIsCountStrategy fails for ConnectiveSteps

### PR DESCRIPTION
**Pull request by dkuppitz**
https://issues.apache.org/jira/browse/TINKERPOP-1742

Fixed a bug in `RangeByIsCountStrategy`.

### CODE REVIEW

**Comment by dkuppitz** [comment]
`docker/build.sh -t -i` succeeded.

VOTE: +1

**Comment by okram** [comment]
VOTE +1

**Comment by robertdale** [comment]
VOTE +1

**Comment by spmallette** [comment]
All tests pass with `docker/build.sh -t -n -i`

VOTE +1

**Pull request closed without merging**
