### PR TITLE
TINKERPOP-1278 : Make implicit relative imports explicit

### PR DESCRIPTION
**Pull request by leifurhauks**
Implicit relative imports break python3 compatibility. This commit
replaces implicit relative imports with explicit relative imports, which
are supported by both python 2 (>= 2.6) and python 3.

### CODE REVIEW

**Comment by okram** [comment]
I tried to merge this but there were two problem:

1.) the PR references old code and thus, lots of conflicts.
2.) graph_traversal and traversal are auto-generated and thus editing the .py does nothing.
3.) Jython complains in JythonScriptEngineSetup (tests don't pass)

If you can fix this PR accordingly, I'd be happy to merge.

**Comment by leifurhauks** [comment]
Brought this branch up to date and fixed the code generators.

**Comment by leifurhauks** [comment]
Added WIP to the title of the PR while I sort out some silly mistakes I made with the conflict resolution...

**Comment by leifurhauks** [comment]
Okay, should be good now

**Pull request merged**
